### ISSUE TITLE
Toolbar options should not be duplicated in Sidebar

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/nova-blocks#10]
@madalingorbanescu recommends in #7 that we have to decide where do we want to keep the controls for the Hero Block ("Content alignment" and "Colors") as they are in both locations: Toolbar and Sidebar.

---

Considering that these are block-level controls and that they will stay outside of a (future) Style Manager system, I would suggest to keep them in the **Toolbar** even though they are needed more screen space than a few simple buttons.

_Block Design best practices: https://developer.wordpress.org/block-editor/designers/block-design/_

**Comment by razwan** [comment]
this is also applicable to the Slideshow block
