### ISSUE TITLE
Review code for WordPress.org Submission

### ISSUE THREAD

**Issue by razwan** [pixelgrade/nova-blocks#11]
@vladolaru we need a quick check on the code quality and coding standards before submitting the plugin to the WordPress.org repository. Can you take a look?

**Comment by vladolaru** [comment]
@razwan @georgeolaru I have made the review and changes.

What remains are the two Unsplash images in `blocks/hero/index.php` that are linked directly. We should use two local images from the allowed sources (Unsplash is not one of them due to license).

**Comment by georgeolaru** [comment]
@vladolaru does it still hold true or we can close it and keep working on #15 ?

**Comment by vladolaru** [comment]
Close it
