### ISSUE TITLE
[Food Menu] Handle long menu item title & price

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#111]
**Describe the bug**
When I am using the Food Menu block and adding a Menu Item with a long title like _Earl Grey Tea Cured Salmon_ and a price like _$10.95 regular / $12.94 large_ some problems may appear, based on browser I am using:
- On Chrome - the menu item title will go on multiple lines: [image](https://user-images.githubusercontent.com/46342490/77450577-1f262080-6dfc-11ea-908b-7bd8fa078ff9.png)
- On Safari - the menu item title will go on multiple lines, but also the menu item with the long title will overlap the menu item before: [image](https://user-images.githubusercontent.com/46342490/77450848-89d75c00-6dfc-11ea-92b7-7144271255d4.png)

It worth to mention that the problem is not related to resolution, it is related to how we handle long menu item titles or prices like _$10.95 regular / $12.94 large_.

@georgeolaru I need your suggestion about how the menu items should look with longer titles and prices.

**Comment by georgeolaru** [comment]
@madalingorbanescu Good catch! Upon the discussion that we had in private, your suggestion on using the [Alignment Shifting](https://css-tricks.com/useful-flexbox-technique-alignment-shifting-wrapping/) technique seems to be the way to go.

The problem that I'm seeing is when such an item is placed in the context of a full menu, there would be mixed items with different styles and (especially) the _Price_ would be harder to scan and read:

![image](https://user-images.githubusercontent.com/1632775/77521249-087ada80-6e8b-11ea-84bd-2f08a76fbd41.png)

I suggest to still make this implementation for _edge cases_ and go a step forward for a final reliable solution.

---

My idea is to impose a rule that shifts the menu style between _classic_ (inline) and _basic_ (row) based on the length of the Title and Price fields. The rule would sound like this:
> Whenever the _Title_ or _Price_ fields are long enough to cover more than one line of text, the entire Food Menu block layout should switch to a basic single column.

![image](https://user-images.githubusercontent.com/1632775/77521965-27c63780-6e8c-11ea-9651-733a35a3fb23.png)
[Figma Document](https://www.figma.com/file/Lm1qjfIbeFHSnX2VQk9EDg/Theme-Rosa-2?node-id=787%3A2)

If there is no way to gracefully* make the switch _automagically_, I would suggest adding a style option for the Food Menu block, so the user could always have the Title and Price on separate rows:

> Menu style:
> - Classic: current implementation with dots
> - Basic: all elements in one column layout 

*It's upon your own interpretation what level of "gracefulness" is acceptable — probably plain CSS is ideal but I'm worried that it's not possible in this context.

**Comment by madalingorbanescu** [comment]
@georgeolaru both suggestions are good, but in my opinion the second solution should be the one to solve our problems using only CSS.

I choose the second one, because a rule to check if Title or Price is long enough to cover more than one line of text it will not cover all the cases. We probably need to know how many characters  can be on the first line of the Menu Item, and if the number of characters from the title plus number of characters from the price is bigger that the number of characters accepted on that line, we should change the layout:
![maxchar](https://user-images.githubusercontent.com/46342490/77539119-84841b00-6ea9-11ea-8fc5-a33b46133884.png)

But my main concern is not that rule, but the fact that users will see different menu layouts based on the device they are using and this may cause confussion.

A new style for the menu block will be a major improvement for the block and will empower the user to choose the layout, based on his needs.

**Comment by georgeolaru** [comment]
I think the users are accustomed to seeing **different versions of a website** depending on the device that they browsing. It's a common pattern to reduce the number of columns or hide some elements that are not essential. The key point is to be consistent within that device — be it one style or another.

My bet is that **counting the number of characters** and identify how many of them could fit in a line of text will have few chances of success. Each character has different widths and it changes altogether when switching the fonts — everything while _the container width remains the same_. 

@madalingorbanescu Thanks for exploring this further! A new style for the menu block is the way to go and I'm glad we came at a point to have a reliable solution. 

I just tested and it works great – nice work! 👏 

![2020-03-25 16-35-28 2020-03-25 16_37_19](https://user-images.githubusercontent.com/1632775/77548506-50175b80-6eb7-11ea-8ffa-ee57f58146c9.gif)

Let's merge this and include it in the next update. Also, please reach Alin and ask him to include a mention about this in the documentation.

Thanks!

**Comment by madalingorbanescu** [comment]
Closed in https://github.com/pixelgrade/nova-blocks/pull/116
