### ISSUE TITLE
Hero of the Galaxy block does not work properly when Pixelgrade Care plugin is active

### ISSUE THREAD

**Issue by Alexandru-Teodorescu** [pixelgrade/nova-blocks#117]
Atunci când adăugăm block-ul **Hero of the Galaxy** și facem click pe imaginea de pe fundal, apare mesajul "**This block has encountered an error and cannot be previewed.**". Problema se poate remedia dacă este dezactivat plugin-ul **Pixelgrade Care**.

Problema se poate vedea în acest [video](https://www.screencast.com/t/06qZSjGGaZ)

**Comment by razwan** [comment]
The issue was related to a bug in **Pixelgrade Care** that was fixed in the last update (v1.7.6)
