### ISSUE TITLE
Media Card Block options not working Lower Screen Sizes

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#121]
I tried today to use the Media Card block, but it seems to not work properly on my 13" MacBook Pro.

It seems like on the small screen, the media gallery and text switch places and the left/right button that changes where the text/image are displayed (right or left) does not work.

I am using the latest version of the Theme (Rosa 2 Version 1.0.5), Nova Blocks Version 1.2.2, Pixelgrade Care Version 1.7.6, Gutenberg Version 7.8.1, Customify Version 2.6.0

Here's a video that proves it: https://share.getcloudapp.com/eDuxDq6Q

**Comment by georgeolaru** [comment]
@andreiungurianu do you think the issue is connected to that laptop screen size (13'') or that's just the environment that you tested?

**Comment by andreiungurianu** [comment]
@georgeolaru I think it's related to the browser tab size. [Here's a recording](https://share.getcloudapp.com/bLumL7ER) on a bigger display where I set the browser window to 1440 x 900 and it works perfectly, but, if I make it a bit smaller, the problem appears again.

It seems like, on my laptop, the browser window (although in Full Screen) has a size that prevents me from using the media card as intended.

**Comment by georgeolaru** [comment]
Got it now @andreiungurianu! Thanks for following-up.
