### ISSUE TITLE
New Advanced "Gallery" Block 

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/nova-blocks#131]
This block is an advancement of the standard Gallery block and its goal is to **display galleries of images in unique and creative compositions**. It will be available as a standalone block under the "Gallery of the Stars" name and also as an integrated part of the Media Card block.

We worked on this for a while on the [advanced-gallery-component](https://github.com/pixelgrade/nova-blocks/tree/advanced-gallery-component) branch, but I don't want to launch it under the radar. I open this issue to figure out the whole package and use it as a reference for the remaining details:

![Screen Recording 2020-04-09 at 04 23 PM](https://user-images.githubusercontent.com/1632775/78899834-9d322a80-7a7e-11ea-8dea-d5f37a85aca7.gif)

While we already have a set of options that are producing quite _amazing results_ without relying on the user to create the layout by-hand, I think it's getting a little complex and overwhelming for first-time users. 

I know that a learning curve is necessary to comprehend all the possibilities, but I believe that we can step up one level and make the "Presets" the go-to place for the average user, while still having an "advanced panel" for users that want to fine-tune all the details.

---

My proposal is to split the options in a tabbed interface with "Presets" and "Customize" tabs, very similar to what we're doing in the [Style Manager](https://github.com/pixelgrade/customify/issues?q=is%3Aissue+style+manager).

![image](https://user-images.githubusercontent.com/1632775/78898283-37dd3a00-7a7c-11ea-8101-a51458e2e567.png)
_[Figma Mockup](https://www.figma.com/file/LkOxQKLMqMpZwBJQiTmmuiYK/Plugin-Nova-Blocks?node-id=1377%3A2265)_

---

@razwan let's get this to the finish line 🏁 Please have a look over and let me know if you have any questions. I did some work for the microcopy and options reorder I will push them shortly.

**Comment by georgeolaru** [comment]
@razwan Do you think that the component is ready for release and we can close this issue?

**Comment by razwan** [comment]
@georgeolaru there are still some issues but I'm working on preparing a new release.

Do you think we can also ship #86 and #87 with the v1.4.0 update? Because those branches are kinda falling behind.

**Comment by razwan** [comment]
I have merged the PR. We will discuss #86 and #87 on another occasion.

**Comment by georgeolaru** [comment]
@razwan I think we will need a bit more time for #86 and #87 — let's catch up on these early next week.
