### ISSUE TITLE
Cards Collection: Remove content padding on Moderate & Highligted Block Area

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#133]
We should have padding for content, only when Content area is set to Moderate or Highlighted. Currently, if I am setting Block Area to Highlighted or Moderate, I will get padding around card content, and this will break the layout.

Here is a comparison between a Cards Collection with Block Area on Basic and a Cards Collection with Block Area on Highlighted:
![image](https://user-images.githubusercontent.com/46342490/78975636-2bf58480-7b1d-11ea-94fb-f9199d07ab6c.png)

**Comment by georgeolaru** [comment]
Fine attention to details @madalingorbanescu! 👌
