### ISSUE TITLE
[Hero Block] Height options does not save.

### ISSUE THREAD

**Issue by Alexandru-Teodorescu** [pixelgrade/nova-blocks#143]
The height options from the Hero Block does not save. You can see that in this [video](https://share.getcloudapp.com/lluDy2xK).

**Comment by razwan** [comment]
The issue wasn't that the option didn't save but rather that it wasn't applied in the frontend but this was fixed in https://github.com/pixelgrade/nova-blocks/pull/140 and shipped with the v1.3.2 update
