### ISSUE TITLE
[Cards Collection] Offer option to align buttons to the bottom

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#146]
I was playing around with all the different ways I can use the new block and in one of my tests, I was trying to create some sort of services packages.

My idea was to create three services, each with a different description and offers.

The problem I faced is that the buttons are placed right at the end of the text and their position depends on where the length of the text. This makes my services plans look a bit off when I save them since the buttons for each of the three services are not aligned. [Screenshot](https://share.getcloudapp.com/z8uxXrQq)

![image](https://user-images.githubusercontent.com/1632775/79990596-eab88980-84b9-11ea-8d9d-1154dd90d8bb.png)

**I thought about two ways this could be improved:**
1. Either make the buttons align to the bottom of the card no matter how long/short the text is. Since each card already syncs its overall height with the card that has the most text in it, the buttons can be at the bottom by default
2. Add a vertical button alignment option in the right panel the same way I can control the text alignment

**Comment by georgeolaru** [comment]
@andreiungurianu Good catch! Let's take this idea into consideration when deciding for #145 

👍 I think the first option could be in line with the first case proposed on issue #145 (making cards having the same height and, subsequently, the buttons always align to the bottom)

👎 I would not go into adding _new options_ currently, especially for a sub-element like buttons.

P.S. Until then, we can take into consideration the `&nbsp;` space for vertical alignment.

**Comment by andreiungurianu** [comment]
Considering the proposal made in https://github.com/pixelgrade/nova-blocks/issues/145 I think the first option is the winner here. 💪

**Comment by georgeolaru** [comment]
@andreiungurianu Let's close this issue then and use it as a **reference**. Once we make a decision in #145, we will make sure to take these insights into consideration.
