### ISSUE TITLE
[Cards Collection] Buttons not working with Gutenberg plugin deactivated

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#147]
If I deactivate the Gutenberg plugin, the buttons in card collection stop working.

[Here's a screenshot](https://share.getcloudapp.com/lluDydKY). I tried to use the recommended action and click "Resolve" but it does not work either.

**Comment by razwan** [comment]
@andreiungurianu Was the block added before or after deactivating the plugin?

The latest version of Gutenberg changed the markup of the button block. So if you added it before deactivating the plugin this may be the reason. So if, the block can be added, saved and edited when the plugin is deactivated there's no issue to be discussed here.

**Comment by andreiungurianu** [comment]
This only happened to previously created card collection blocks that I saved before I deactivated the Gutenberg plugin.

If I add another Cards Collection block now that the plugin is already deactivated, everything works.
