### ISSUE TITLE
Controls on the Map can't be used

### ISSUE THREAD

**Issue by Alexandru-Teodorescu** [pixelgrade/nova-blocks#148]
The controls on the map can't be clicked - [video](https://share.getcloudapp.com/7Ku0065W)

Quick fix using css: 

```
.novablocks-parallax {
    pointer-events: all;
}
```

**Comment by georgeolaru** [comment]
@Alexandru-Teodorescu Can you share an URL of a client that has this issue or the block settings that you use? I'm not seeing the same controls on our demo: https://share.getcloudapp.com/2NuXX7WK

**Comment by Alexandru-Teodorescu** [comment]
@georgeolaru Of course, here's the [link](https://pumpsushiandthai.com/contact/) to the website. Also, I forgot to mention that the **Show Controls** option from **Map Design** needed to be switched on in order to see the controls on the map, sorry. Here's a [video](https://share.getcloudapp.com/rRu9lQXR) to show you what I mean.

**Comment by razwan** [comment]
Added back `pointer-events` to the parallax container, that were removed in #106 and caused the issue, as I couldn't reproduce the Safari issue. @madalingorbanescu do you still encounter the issue described in #106 ?

**Comment by madalingorbanescu** [comment]
Hey @razwan,

I've tested with Safar Version 13.0.1 (14608.2.11.1.11) and I am not encountering the issue described in #106. I think the issue can be closed now.

**Comment by razwan** [comment]
Thanks!
