### ISSUE TITLE
Media Card images not showing on live website

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#153]
**Describe the bug**
After the latest update it seems like the Media Card images are working in the Gutenberg editor and but are not displayed when I view the page live. 

The Media Card blocks affected were configured before the update. If I insert a new Media Card block, the images display just fine. This means all live websites will be hit by this issue. 

I'm using Nova Blocks 1.4.0, Rosa 2 v1.1.0, and the latest version of Pixelgrade Care (1.7.8)

**Gutenberg**
![Image 2020-04-30 at 11 01 57 AM](https://user-images.githubusercontent.com/53944294/80687199-9cffda80-8ad2-11ea-9a26-89e932c1e39c.png)
**vs Live page**
![Image 2020-04-30 at 11 02 10 AM](https://user-images.githubusercontent.com/53944294/80687210-a1c48e80-8ad2-11ea-8def-99742e5412d0.png)

**Comment by razwan** [comment]
fixed in 486fe7b228139eb9aa435d272996166a7715701a and shipped with v1.4.1
