### ISSUE TITLE
Media Card: Images and text not showing side-by-side in lower screen resolutions

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#155]
**Describe the bug**
Any resolution (or Chrome browser window size) below 2560 x 1440 makes the image gallery and text align one under the other instead of side by side.

The odd thing is that some Media Cards work in certain screen resolutions, while others don't and it seems to affect the Media Card blocks already created before the latest updates. If I create a new one, it shows just fine.

Video for the issue recorded at 1650px x 1050px - https://share.getcloudapp.com/nOu8oGWE

I tried tweaking the just-released Gallery presets, saving the page again, but nothing worked.

I'm using Nova blocks 1.4.1, Rosa 2 1.1.0, and WordPress 5.4.

**Comment by georgeolaru** [comment]
@razwan could you please take a look over this?

**Comment by madalingorbanescu** [comment]
The problem was caused by the default behavior of flex. More info about that here: https://stackoverflow.com/a/38224283
