### ISSUE TITLE
[Mobile] Media Card Block images wrongly displayed

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/nova-blocks#156]
**Context:**
WordPress v5.4.1, Nova Blocks v1.4.1, Rosa 2 Lite 1v.1.5

**Media Card Constellation**, using the following presets:
- _The Cloud Atlas_
- Image resizing → _Stretch to fill the container_

**Results on mobile**

![Screen Recording 2020-05-01 at 04 13 PM](https://user-images.githubusercontent.com/6790170/80808453-470d5e80-8bc8-11ea-96c1-1045e199677f.gif)

**Comment by madalingorbanescu** [comment]
This issue is related to a style that is coming from Rosa2 Lite. I am going to close the issue on this repo and will continue the discussion [here](https://github.com/pixelgrade/rosa2-lite/issues/21).
