### ISSUE TITLE
Improve "Show Street Labels" copy for the Map Block

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#158]
Disabling "Show Street Labels" makes the "Show Nearby Venues" dissapear as well although it still shows as being enabled.

Here's a video that shows this issue: https://share.getcloudapp.com/E0ubX7J8

I'm using Rosa version 1.1.0 and Nova Blocks 1.4.1.

**Comment by razwan** [comment]
@georgeolaru this seems to be intended behavior. I can't remember for sure, but the attributes are called **showLabels** and **showIcons** and my guess is only the labels were altered later on. 

However, we could change the toggles to work one for venues (labels and icons) and one for roads (labels only). What do you think?

**Comment by georgeolaru** [comment]
@razwan You're right! Sorry for the confusion — I tested again and I think it works as intended: 
- The "Show Nearby Venues" is hiding venue icons + labels
- The "Show Street Labels" is hiding all the labels (street + venues) for a very minimalistic (but imprecise) view.

The only change I would suggest is to simplify the "Show Street Labels" copy to only "Show Labels"

![CleanShot 2020-05-15 at 15 31 57](https://user-images.githubusercontent.com/1632775/82050739-5957c400-96c1-11ea-8edd-7863a00be158.gif)
