### ISSUE TITLE
Create a Demo Preview site for blocks

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/nova-blocks#16]
It could be useful for users to have a full demo preview of how Nova Blocks could look like by default.

Let's use the installation that we used on wpsandbox.io and install it on http://demos.pixelgrade.com/nova-blocks

@razwan As a bonus, it would be great if we can use the complementary Nova Theme for the showcase.

**Comment by vladolaru** [comment]
On it.

**Comment by georgeolaru** [comment]
The site is already online at https://demos.pixelgrade.com/nova-blocks/

Thanks @vladolaru!
