### ISSUE TITLE
[Hero Block] Using a Custom value for Layout Content Width makes the Hero Block text look bad on mobile

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#163]
When I use a custom value for the Layout Content Widht for the Hero Block the settings apply to the mobile version as well, making the text crammed in a small space

Here's the Hero block on mobile with Layout Content Width set at 50%:
![Screenshot 2020-05-21 at 12 28 13](https://user-images.githubusercontent.com/53944294/82544972-9ce97c80-9b5e-11ea-8d63-ddfa88b306c6.png)

![Screenshot 2020-05-21 at 12 16 53](https://user-images.githubusercontent.com/53944294/82545019-b25ea680-9b5e-11ea-9e8f-c8cff8e496e7.png)

I'm using Nova Blocks 1.4.2 and Rosa 2 v. 1.2.0

**Comment by georgeolaru** [comment]
Good catch @andreiungurianu! 

On mobile devices I think we should simply **reset** the _Width_ and _Padding_ to the desired value set by default in the theme. (eg. 100% for width and 8% for padding)
