### ISSUE TITLE
[Headline] Headline text is missing a space between each text row

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#179]
I was testing the headings distribution for certain pages and I noticed that the text added via the Headline block is missing a space between the text above and the text below.

![Screenshot 2020-07-07 at 14 12 07](https://user-images.githubusercontent.com/53944294/86772056-fb5db200-c05b-11ea-9673-b4a1ff6f5f4d.png)

This means that Google sees the headlines on a page like this:
![Screenshot 2020-07-07 at 14 15 36](https://user-images.githubusercontent.com/53944294/86772288-61e2d000-c05c-11ea-8879-9ecfe5459e36.png)

This can be temporary fixed by adding a space after the text in the top row, but it should be automatically added by the block.

**Comment by razwan** [comment]
@andreiungurianu I added whitespace between the elements of the Headline blocks. However, every page needs to be saved in order for this change to take effect.

**Comment by andreiungurianu** [comment]
Thanks for fixing this.
