### ISSUE TITLE
Add Caption/Description support for Images

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/nova-blocks#186]
In my brief research, I found out an article called "[Title, Caption, Alt Text, and Description: Harnessing the Power of WordPress Image Metadata](https://mor10.com/power-of-wordpress-image-metadata/)" by Morten Rand-Hendriksen, which explains pretty well the options that we have to display meta-information about images in a gallery 

For clarification, I will quote the definitions of _Caption_ and _Description_ fields:

> **Caption**: The caption is the text traditionally displayed underneath the image though the exact placement will vary depending on your theme. The caption is not tied to the attachment post but to where you choose to place the image in a post. That means if you use the same image in several different posts or several different places within a post you can have **individual captions for each**. It is worth noting that WordPress image captions can contain HTML including links.
> 
> **Description**: The Description field is probably the best-kept secret of images in WordPress. If you add text to the description field that text will be stored as post content for the attachment post. That means if someone lands on the attachment post page for the image they will see the long description (provided the current theme supports it).

So, while the _Description_ is unique for an image no matter where it is placed, the _Caption_ is location-specific and can be changed or removed depending on the context. Different from _Alt_ and _Title_ attribute, the _Description_ and _Caption_ don't seem to have an impact on SEO or accessibility, so we can use them interchangeably for presentation purposes.

---

Whenever we want to display those details (in this case is Advanced Gallery block), I suggest to add them below the image with the following styles:
- _Caption_ using the Heading 4 font style (similar to the titles from Cards Collection block)
- _Description_ using the Body font style (eg. the smaller paragraph version)

![image](https://user-images.githubusercontent.com/1632775/88033535-2a8a1e00-cb48-11ea-960c-5ad311b6ac5c.png)

**Comment by georgeolaru** [comment]
After a brief discussion with @razwan we agreed to add two CSS helper classes that could be added as a wrapper for both Description and Caption (eg. `<p class="name"> content </p>`), as follows:
- `.credits` to drastically reduce the font style visibility; this is a good option for credits (eg. _Photo by Author from Source_)
- `.hover` to display the element only when hovering the image

**Comment by madalingorbanescu** [comment]
Closed in https://github.com/pixelgrade/nova-blocks/pull/187
