### ISSUE TITLE
[Slideshow Block] Can't see my images in the Gutenberg editor

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#189]
Since the latest update to Nova Blocks 1.5.1 I noticed that I can't see the slideshow images in the Gutenberg editor. As you can see in the screenshot below, everything is black:

![Screenshot 2020-07-23 at 15 43 24](https://user-images.githubusercontent.com/53944294/88287641-3ff37980-ccfb-11ea-80ab-7aec17b113b2.png)

At the same time, when I go to the "Slides" tab in the settings panel I see this:

![Screenshot 2020-07-23 at 15 44 25](https://user-images.githubusercontent.com/53944294/88287747-6addcd80-ccfb-11ea-9f99-699d5ad28138.png)

The images I had selected before the update do show up on the live website just fine. I also tried to re-select the images or change them, but even though the images display on the live website, in the editor all I see is a black screen.

**There's also a noticeable loading lag** on the live website (there are black spots that show up before the image loads). Plus the animation when I scroll between the images in the slideshow is really slow. I'm adding it here because it might be related. [Here's a video](https://share.getcloudapp.com/6qu26dn8).

I'm using Nova Blocks 1.5.1 and Rosa2 version 1.3.0

**Comment by razwan** [comment]
Fixed in e0b13424cc5f069ea6311b4251aeeb23bca18a6b and updated plugin
