### ISSUE TITLE
Add Block: Food Menu

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#19]
Create a block that allows us to create food menus similar to menus present in [Rosa](https://cl.ly/2607f3c4cd16) and [Osteria](https://cl.ly/010f735d8aad).

My initial proposal will be a parent block ( Food Menu ), with settings for styles ( solid or dotted ) and layout ( list or grid ). Plus a child block ( Food Menu Item ) with settings for alignment and an option to make it featured ( [example](https://cl.ly/4a59ca7c3e56) ) 

This block should output:
- Menu Section Title 
   - Menu Item Title
   - Menu Item Description
   - Menu Item Price

## → [Document (Dropbox)](https://paper.dropbox.com/doc/Block-Food-Menu--AjsxuVLeQx4i2byNkSShdsxiAg-q7Fce55dzxImmQegDll2N)

**Comment by georgeolaru** [comment]
@madalingorbanescu Great job so far! 👏 

I tested it with multiple themes (Twenty Nineteen, Storefront, Atomic, etc) and it's looking great. 

Few things that I noticed:

- We're missing an _Alignment_ for _Wide_ option, so the 2-columns menu has enough space to breathe.
- We might need to remove the default spacing for _Menu Item Title_ (H4) and _Description_ (P).
- Add some margin-top of 1.5em to _Sections Title_ (except the first one, as it needs to be aligned with the second column)
