### ISSUE TITLE
Parametric Layout Generation for Cards Collection block

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/nova-blocks#190]
After setting up the foundation by creating the [Cards Collection](https://github.com/pixelgrade/nova-blocks/issues/105) block, let's get it to the next level with a _parametric layout generator system_. 

We will work on it initially on the **Posts Collection** block variation, leaving the door open for this system to _afford_ the support of other similar blocks (e.g. Cards, Products, or Projects Collection).

---

@vladolaru presented a great demo of the layout generator using a set of parameters that can be seen live on https://advanced-posts-collection-layout-system.netlify.app/

![image](https://user-images.githubusercontent.com/1632775/88295406-0ecc7680-cd06-11ea-9457-d38b72cfe702.png)

---

Let's use the CSS grid produced by the system above, move it to the WordPress editor (if necessary), load it with various cards according to the data provided by the generator, and see how it works.

We will make further decisions once we can play with some real content (eg. posts).

**Comment by georgeolaru** [comment]
@razwan I made an in-depth round of testing and I attached my findings and overall feedback. Nice work and excellent progress! 💪 

---
🇷🇴  &nbsp; [Feedback for Parametric Layout Generation.pdf](https://github.com/pixelgrade/nova-blocks/files/5117965/Feedback.for.Parametric.Layout.Generation.pdf)

**Comment by razwan** [comment]
Hey @georgeolaru!

Thanks for your feedback! Going through the document you provided I made quite a few changes to the way the generated grid is filled with cards and the way in which these cards are displayed. It was a lot of back-and-forth trying to make all the presets work at the same time while making these changes. Overall the changes may be subtle but can greatly affect the generated layouts.

I'll try go briefly to the points in the documents and state what I've done related to that.

1 - Added font-size modifier classes for meta, content and buttons and made minor adjustments for cards w/ small width.
2, 3 - Made the required adjustments but some thing may still need to be tweaked for proper spacing and hierarchy
4 - This is a tricky one as new cards are added based on the configuration of the areas generated and not by their visual appearance. I tried to improve to algorithm while also keeping the initial distribution for the presets we have now.
5 - Made the widest column generated by the layout have the featured article (even though there are some cases where the feature size option describes the featured area as being smaller then others)
6 - Added the collection header component from the classic grid component
7 - The classes weren't properly added so I fixed that
8 - Added a radio control to switch between portrait and landscape and added the width classes based on the number of columns
9 - Added the container height option from the Advanced Gallery component, but didn't set a value for it for every preset

10 - The expectation is partially right. Changing the featured position setting causes the other columns to be merged but this can be prevented using the Columns Fragmentation setting.
11 - _there was no content for this point_
12 - I tweaked the preset a little, also added a new preset similar to this one but closer to the reference from my point of view. Regarding the card distribution thing should behave better now. Also see point 4.
13 - See point 5.

---

**Note:** 
TR 47: it is a tiny bit different than how it was before but I don't see it as a bad thing.
TR 12: I had to change some attribute values to be able to obtain the same layout
TR 10: Has many landscape cards now. I don't think we can obtain the previous layout now. However there are many awesome layouts that can be obtained and I believe we can get rid of this one and add better ones.

The things we should focus on from now on are responsiveness and rendering on the frontend. I'll have a go at rendering meanwhile.

---

Please have a look, make a few clicks and let me know what you think.

Cheers!

**Comment by georgeolaru** [comment]
Thanks, @razwan! I confess that I've got some butterflies in my stomach while testing the system in its current state :-) things are looking great and the cards seem to stick together in unexpected ways, even when randomly generated.

The only issue that I notice is with No. 6 where the _Title_ and _Subtitle_ options do not seem to _Save_.

Let's move forward: I will focus on labeling (copy) and re/ordering the options, while you should continue with the responsive and frontend rendering.

---

_Sidenote: I think it's a good idea to keep the _Debug Parameters_ in place as they are very useful for testing. Maybe we can put them behind a flag in Pixelgrade DevMode. Please take a shot whenever you have a chance._

**Comment by razwan** [comment]
Hey @georgeolaru 

I just finished implementing the render method for the frontend and even the implementation for the grid to respond to the window size. It basically removes columns progressively while the window width gets smaller. Also on mobile devices all cards become portrait and all elements of the cards become the same sizes. You can test this on the [advanced-posts-collection-controls](https://github.com/pixelgrade/nova-blocks/tree/add/advanced-posts-collection-controls) branch.

For the moment the responsiveness only works in the frontend, and I don't really fancy trying to replicate this in the backend and there are more important things to be done. From my point of view, the things that are left to be done are the following:

1. Improve the randomisation of the layout. Currently there are some cases where the layout actually breaks, the main problem from what I can see is when the _Hierarchy Crossing_ attributes comes into play. We could either keep this attribute and randomness to the max and try to find a workaround the issue, or we could be more restrictive with the randomness of each attributes and maybe remove the Hierarchy Crossing attribute.
2. Check the _Title_ and _Subtitle_ fields
3. Make the Color Contrast controls work properly
4. Make the Spacing controls work properly
5. Create some sort of framework for declaring debug controls that can be enabled with WP_DEBUG or another global constant

Please let me know if you get the chance to test this and also if there is anything I may have overlooked

**Comment by georgeolaru** [comment]
Hey @razwan! I just tested the latest improvements and I noticed a few more things:

1. The responsive implementation is awesome! I'm glad that we can control the layout using the _"columns"_ parameter. One thing I would like to suggest: can we explore what is happening if we keep the levels of hierarchies on mobile devices? I made some explorations [here](https://www.figma.com/file/ZuwpRb98jZSFtTQG8WPF1df5/Upstairs?node-id=195%3A722) and they seem to work well. 

2. There seems to be some extra spacing added with the new Emphasis support:

![image](https://user-images.githubusercontent.com/1632775/92239437-aefbea80-eec3-11ea-8ea8-39aa3912f8a9.png)

3. The cards have links only on the "read more" button — can we extend this all over the card elements, in the same way that we have on our [blog](https://pixelgrade.com/upstairs/)?

4. On the "Set up elements for this block" section do you think we can use _inactive_ elements to simply _always_ hide them from the cards? (exception is the "Subtitle" which probably should be removed altogether)

4. The "Layout" options seem to be available now on the "Cards Collection" block, but they don't seem to work. This would be a nice way of componentization, but if it's not working yet, you can remove it from the "Cards Collection" block for now.

**Comment by madalingorbanescu** [comment]
Hey @razwan,

I knew that the layout generator is going to be awesome, but now when I’ve tested in-depth I’ve to say that it’s more than amazing. Congrats to you and @georgeolaru for your hard work.

While testing the block, I’ve noticed a few things that should be fixed and some that need some improvements:

1. While on the frontend, the meta of the card has a font-weight 600, in the editor is 400. From what I saw, 'is-style-meta' class is missing in the editor.
2. In the editor, the separator between meta is missing spacing: https://share.getcloudapp.com/rRu7DQYe
3. Regarding the issue with the read more link — I saw the discussion that it should be on the whole card. However, giving the fact that we are showing some metas like date and category, maybe we should add a link on those too (date and category) and made sure that they are clickable.
4. The toggle for elements that are being used is not working: https://share.getcloudapp.com/5zuGK2kl, except Collection Title and Collection Subtitle
5. If I am trying to add an additional class for the block, the class is not being shown in the markup.
6. Maybe on smaller grid areas, where post excerpt is not being shown, the Read More button should not be displayed.
7. When the post is on a small grid area and it’s in landscape, I think it looks better without the image: https://share.getcloudapp.com/Z4ukNnzJ   

Everything works great and the layout presets helped a lot, by giving me a starting point and helping me to understand better the settings.
Let me know what do you think about my suggestions and if you need help in solving any of those issues you can ping me anytime 😁

**Comment by georgeolaru** [comment]
PS: Nice commits messages @razwan — they are really helpful to get a glimpse of the progress.

**Comment by georgeolaru** [comment]
@razwan Regarding the [request](https://github.com/pixelgrade/nova-blocks/issues/190#issuecomment-687187136) for the _New Yorker_ preset, here is the real-life example of what the [New Yorker](https://www.newyorker.com/) site does with cards on smaller resolutions. Other examples could be [Vogue](https://www.vogue.co.uk/), [The Ringer](https://www.theringer.com/) or [The Atlantic](https://www.theatlantic.com/world/).

I would only pay attention to the mobile version where there are still two levels of hierarchy (portrait + landscape)—if we can achieve something similar I think we're good-to-go.

![image](https://user-images.githubusercontent.com/1632775/92564832-7886ec80-f282-11ea-8ed2-1128ac67c2bd.png)


---

Now, until we have the face-to-face discussion tomorrow, here are a few small things that I notice:

- [ ] TR 30 and 12: featured post do not show with the default number of posts

![CleanShot 2020-09-09 at 09 40 26](https://user-images.githubusercontent.com/1632775/92563661-92bfcb00-f280-11ea-9947-80ee26d68d00.gif)


- [ ] Editor: The Collection Subtitle seem to get behind cards wrapper: 
![CleanShot 2020-09-09 at 09 18 41](https://user-images.githubusercontent.com/1632775/92561816-91d96a00-f27d-11ea-9c29-87c9f532769b.gif)

- [ ] The Title+Subtitle group could better use _vertical spacing_ to create the hierarchy between [Title+Subtitle] and [Cards]. _Note that in the case of the **Parametric** layout the spacing between [Title+Subtitle] and [Cards] is larger; still, the space from Title and Subtitle should be smaller._

![image](https://user-images.githubusercontent.com/1632775/92562837-458f2980-f27f-11ea-99d3-1743878c6278.png)

+ the cards description font-weight issue from the Editor mentioned by @madalingorbanescu above
