### ISSUE TITLE
Block Areas: Show Block Areas only on theme that are using them

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#191]
**Is your feature request related to a problem? Please describe.**
Currently, when I am installing Nova Blocks, I am getting a new menu item called _Block Areas_ under the Appearance section WordPress Dashboard. If I am accessing Block Areas, I am also getting 3 Block Areas created: Promo Bar, Header, and Footer. All of them are created for Rosa2 and should be shown only on Rosa2. 

**Describe the solution you'd like**
I think we should [load the file `block-areas.php`](https://github.com/pixelgrade/nova-blocks/blob/e0b13424cc5f069ea6311b4251aeeb23bca18a6b/nova-blocks.php#L126) only when block areas are used in the current theme.

**Comment by vladolaru** [comment]
@madalingorbanescu What you propose is to have Rosa2 declare support for `block-areas`.

But, I think we may have bigger issues: from what I see the block-areas plugin is stale https://wordpress.org/plugins/block-areas/ We may be chasing the wrong issue here.

**Comment by razwan** [comment]
Hey @vladolaru

I don't see a big issue with the Block Areas plugin being stale. Until full site editing reaches core and we can rely on the template parts implementation in core, the Block Areas plugin is just enough. It doesn't seem to me that there's any need for further development or bug fixes in the plugin

**Comment by vladolaru** [comment]
Ok @razwan I trust you.
