### ISSUE TITLE
Hero block can't be selected from the inserter

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/nova-blocks#197]
While searching through the blocks, if you want to use the Hero of the Galaxy block, you can't, because when hovering over the block, the window is closing. I've made a short video for a visual explanation — https://share.getcloudapp.com/o0u8gdoP

I noticed it happens on **WordPress 5.5**

**Comment by georgeolaru** [comment]
@razwan Can you look over this issue and see how it's linked to the Nova Blocks plugin?
