### ISSUE TITLE
Focal Point Picker: Guidelines Misalignment 

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/nova-blocks#198]
In the 8.7.1 version of Gutenberg (the latest) I noticed that the guidelines that we added for center alignment are no longer aligned with the center of the pointer. 

It might be in conflict with the 9x9 grid that was added [recently](https://github.com/WordPress/gutenberg/pull/22531), which I don't think it adds much value in this case—the focus is on the pointer as a reference point, not on the container boundaries which are constantly changing according to the block or browser size. If it makes things easier to fix, we could take into consideration the option of removing the 9x9 grid.

![CleanShot 2020-08-17 at 11 42 48](https://user-images.githubusercontent.com/1632775/90376254-d73fb880-e07e-11ea-8667-d6b88cd779b1.gif)

**Comment by georgeolaru** [comment]
@razwan did you succeed in finding a solution for both WordPress 5.5 and the latest version of Gutenberg (8.7.1+)?

**Comment by razwan** [comment]
Yes, I tested on both WordPress 5.5 and the latest version of Gutenberg. I found one class added to the focal point picker component that was added recently and used that. Hopefully it will stay like that, but I think it's the best we can do right now. 
If anything goes south we can ditch the old styling once 5.6 rolls out.

**Comment by georgeolaru** [comment]
@razwan Got it! Great approach.
