### ISSUE TITLE
[Slideshow Block] Some options are broken

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#206]
**Describe the bug**
While trying to recreate a performance issue reported by @andreiungurianu, I found some other issues:
- [x] The parallax is slow sometimes: https://share.getcloudapp.com/7KuLZZBr
- [x] ~~Navigation arrows are not perfectly centered.~~
- [x] ~~Navigation arrows are not having the same style in the editor, compared to frontend.~~
- [x] The minimum height option is not working.

**Comment by razwan** [comment]
Hey @madalingorbanescu,
Giving my 2 cents regarding the issues described above:

> The parallax is slow sometimes: https://share.getcloudapp.com/7KuLZZBr
The placeholder images fetched from Unsplash are way too large, we should probably not use the url of the full sizes image when normalising the images received from the unsplash API.

> The minimum height option is not working.
My felling is that the Minimum Height option is working but the way it is intended to work should be documented better and a link to the documentation should probably be added in the description of the field.

The way in works is that the height is set to the max between the following values:
1. Value of the Minimum Height option
2. Content height of every slide (more content makes the slider taller)
3. Aspect ratio of every image used as background (portrait images make the slider taller)

@georgeolaru can you confirm that this was the intended behavior?

**Comment by georgeolaru** [comment]
@razwan I can confirm the intention for the slideshow height that is set from the three conditions already mentioned in the documentation: https://pixelgrade.com/docs/rosa2/blocks/slideshow/

![image](https://user-images.githubusercontent.com/1632775/92391314-15cc0e80-f125-11ea-80c6-1293dc6d74f2.png)

---

@madalingorbanescu can you test using the logic above and see if it works as intended?

**Comment by madalingorbanescu** [comment]
Hey @georgeolaru,

I've tested the Slideshow block and you're right. It works exactly how it is documented. To avoid further situations I think we should consider @razwan idea about a link to documentation in the description of the field.

**Comment by madalingorbanescu** [comment]
The navigation arrows style inside the editor was an issue related to Rosa2, so I am going to open an issue that repo and continue there.

**Comment by madalingorbanescu** [comment]
Closed in https://github.com/pixelgrade/nova-blocks/pull/212
