### ISSUE TITLE
[Media Card] Image Position and Image Resizing not working in editor

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#210]
I noticed that the two controls - Image Position and Image Resizing - found in the Media Composition section from the Media Card block are not working in the WordPress editor. When I hit publish, I can see the changes on the website but in the editor nothing changes.

Here's a demo video:
[Issue Nova Blocks Media Card Media Composition controls.mp4.zip](https://github.com/pixelgrade/nova-blocks/files/5217028/Issue.Nova.Blocks.Media.Card.Media.Composition.controls.mp4.zip)

I'm using Nova Blocks 1.5.3 and Rosa 1.4.0 with WordPress 5.5.1

**Comment by madalingorbanescu** [comment]
Hey @andreiungurianu,

Thank you for testing and reporting back this issue.
I've made a commit and this issue will be fixed in the next update.
