### ISSUE TITLE
[Media Card] The ability to remove left and right side spacing

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#225]
I was trying today to obtain a design where the left or right images of the Media card can go all the way to the edge of the browser tab, without having any margins. Similar to what I can do for the top and bottom spacings for the block—where I can remove them completly.

I tried to achieve that but it seems like I can't full width with it—the best I can do is by sliding the Container Width from Customizer -> Theme Options -> Layout to the max. 

Below is an example. On the left is the design I was trying to copy and on the right is what I got and the spacing I'm talking about.

![Screenshot 2020-10-15 at 13 00 12](https://user-images.githubusercontent.com/53944294/96108718-99c4a380-0ee6-11eb-948e-2aa19b9b59ff.png)

I know that the container widght is necessary, but I'm sure there must be a way we can enable images to have no margins on the left or right side.

This is, of course, up for discussion and I'm interested in hearing your thoughts.

**Comment by georgeolaru** [comment]
We can do that now using the `Alignments` controls:

https://user-images.githubusercontent.com/1632775/175485710-ebec8c0a-9ce2-40b2-bf0b-eec50807c08e.mp4
