### ISSUE TITLE
[Media Card] Emphasis by Contrast broken

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#229]
While testing the latest version of Nova Blocks, I have found a small issue with the option Emphasis by contrast in Media Card block.

If I am setting Emphasis by Contrast on 3, this means that **Block Emphasis** is on _Moderate_ and **Content Area Emphasis** is on _Basic_, the block in the editor is different than the block rendered in the frontend.

[Editor](https://user-images.githubusercontent.com/46342490/96712756-4780f800-13a8-11eb-98a5-05dfe22aed12.png)
[Frontend](https://user-images.githubusercontent.com/46342490/96712892-79925a00-13a8-11eb-8148-7d95bd30fa3c.png)

It looks like on the frontend, the block is rendered with **Block Emphasis** on _Moderate_ and **Content Area Emphasis** on _Moderate_.

**Comment by razwan** [comment]
Hey @madalingorbanescu,

I checked this on the `fix/frontend-assets` branch and everything seems just right.

Editor
![Screenshot 2020-11-05 at 14 14 37](https://user-images.githubusercontent.com/1633371/98240120-a0888880-1f71-11eb-9e4c-6fd1a100fd09.png)

Frontend
![Screenshot 2020-11-05 at 14 15 05](https://user-images.githubusercontent.com/1633371/98240143-a8e0c380-1f71-11eb-89e9-87e07885bcc4.png)

Setting this to invalid and removing it from the milestone
