### ISSUE TITLE
New "Shape Modelling" tool

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/nova-blocks#234]
### Initial proposal:
![Slice 1](https://user-images.githubusercontent.com/1632775/97539519-c4c0f400-19ca-11eb-8536-aa85806f7a3d.jpg)

### Current progress:

Media Card blocks with Single images | Two images
------------ | -------------
![image](https://user-images.githubusercontent.com/1632775/97540336-2c2b7380-19cc-11eb-992d-672ceb5bc5e3.png) |  ![image](https://user-images.githubusercontent.com/1632775/97324851-fcb92180-187a-11eb-86d6-6531a9c0285c.jpg)

**Comment by razwan** [comment]
I've merged #238 into `release/v.1.7.0` branch.

**Comment by georgeolaru** [comment]
Nice! Congrats @razwan! 👏
