### ISSUE TITLE
[Cards collection] Support for transparent background images

### ISSUE THREAD

**Issue by ilincaroman** [pixelgrade/nova-blocks#240]
**Is your feature request related to a problem? Please describe.**
I am using for the Cards collection widget some PNGs which have a transparent background and also have various aspect ratios. There are two issues that make them display a bit odd (screenshot attached):
1. Background colour that is different from the module background. I assume this is because there is a set background colour for the card images?
2. Image is set to fit container. My goal here is to display the PNGs at their original aspect ratio or at least without cropping.

**Describe the solution you'd like**
1. Is the background colour necessary considering that if you'd use a JPG or any photograph, you wouldn't need the background colour anyways?
2.  I would expect a switch from "fill container" to "fit to container" for the card images? 

**Describe alternatives you've considered**
1. I was looking into changing the colour palette to be less diverse, but I am loosing some contrast between other sections, which is not ideal. Of course I can always CSS it.  
2. On the cropping, I could look into resizing them in square images in Photoshop as an alternative.

**Additional context**
<img width="1378" alt="Screenshot 2020-11-09 at 20 39 48" src="https://user-images.githubusercontent.com/15910943/98593865-b8427280-22cb-11eb-97f2-cdd3a99418db.png">

**Comment by madalingorbanescu** [comment]
Hey @ilincaroman,

Thank you for opening this issue 😇

You are right about the background color for the card images, but while testing it I saw that this is happening only in the editor, not the frontend. However, this background should be visible only when an image has not been set.

Regarding an option that can control image resizing, it actually exists. You can find it while editing the **Cards Collection** in the **Display** section:
![image](https://user-images.githubusercontent.com/46342490/98647079-004dad80-233d-11eb-8a34-74fdd99a3805.png)

Please let me know if you managed to set the images to fit the container.

**Comment by georgeolaru** [comment]
Good points @ilincaroman! Thanks for stepping in

While the "Image resizing" option solves your latter problem, the first one seems to be a bug as there shouldn't be any background on the cards—unless you set one using the "Color Contrast" module, which is not the case.

---

@madalingorbanescu can you remove that background and test it with the options from "Color Contrast"? [Here](https://www.figma.com/file/LkOxQKLMqMpZwBJQiTmmuiYK/Plugin-Nova-Blocks?node-id=2287%3A0) are all the use-cases and how it should look:

![image](https://user-images.githubusercontent.com/1632775/98655647-5d9b2c00-2348-11eb-8807-63541e7001e5.png)

**Comment by ilincaroman** [comment]
@madalingorbanescu Ah, amazing, didn't spot the fit option! Thanks.
On the background issue, I see it happening on front-end as well. I see you're looking into it, let me know if it's still valid :)

**Comment by madalingorbanescu** [comment]
Hey @ilincaroman,

I have just made a commit with a fix for this issue. The fix will be live in the next update of Nova Blocks (1.7.0).
The next update will be launched soon, but if you need to fix the background sooner, you can use the following CSS snippet:

`.novablocks-card__media-wrap {
    background: transparent;
}`

Let me know if that worked 🤗

**Comment by ilincaroman** [comment]
@madalingorbanescu Worked like a charm.

I'll have to throw another curve ball though: I used the "overlapping" option, but it seems to cut a lot of spacing from the bottom as well. Assumed it might be particular only to cards with title only, but tried inserting buttons too and same issue.

<img width="2416" alt="Screenshot 2020-11-10 at 18 03 00" src="https://user-images.githubusercontent.com/15910943/98713028-fa78bc00-237e-11eb-8d77-9ac70354f2c7.png">

<img width="2559" alt="Screenshot 2020-11-10 at 18 04 35" src="https://user-images.githubusercontent.com/15910943/98713199-33b12c00-237f-11eb-95f6-1ddfa6e2cf8b.png">

**Comment by georgeolaru** [comment]
@ilincaroman You don't need to use the "overlapping" option if you don't want to actually overlap those blocks. Use the "Content Area Spacing" and/or "Block Spacing" option to space between blocks:

![Screenshot2020-11-10 at 20 28](https://user-images.githubusercontent.com/1632775/98715965-84328480-2393-11eb-9dc9-1b1ddca9cf0e.gif)
