### ISSUE TITLE
[Cards collection] Multiple rows and more cards

### ISSUE THREAD

**Issue by ilincaroman** [pixelgrade/nova-blocks#241]
**Is your feature request related to a problem? Please describe.**
I can't seem to understand if I can add more than 4 cards or multiple rows in a Cards collection. I am blocked at 4 without any "+" displaying to add more.

**Describe the solution you'd like**
Support for more than 4 cards/multiple rows? 

**Describe alternatives you've considered**
I considered adding another Cards collection module, but worried about spacing between them not being consistent.

**Additional context**
<img width="1284" alt="Screenshot 2020-11-09 at 20 54 25" src="https://user-images.githubusercontent.com/15910943/98595322-c1ccda00-22cd-11eb-88e0-a8265d5be15e.png">

**Comment by madalingorbanescu** [comment]
Hey @ilincaroman,

There can be only 4 cards in the Cards Collection, but you can always add a new collection and on the second Cards Collection block you can enable overlapping. This setting can be found in the Space and Sizing section. Here is a short video of me doing that: https://share.getcloudapp.com/p9uwJOr2

_This setting will remove the top spacing from the second block and will make spacing more consistent._

**Comment by ilincaroman** [comment]
@madalingorbanescu Ah, so that's what that means :) Great. Is this an option for any of the Nova modules?

**Comment by madalingorbanescu** [comment]
Hey @ilincaroman,

I've edited my previous comment because @georgeolaru proposed a better solution to your problem [here](https://github.com/pixelgrade/nova-blocks/issues/240#issuecomment-724885637).

The spacing section is currently available in the following blocks: _Media Card Constellation_, _Cards Collection_, and _Posts Collection_.
