### ISSUE TITLE
[Media Card] Improve "Change Media" Discoverability

### ISSUE THREAD

**Issue by ilincaroman** [pixelgrade/nova-blocks#242]
**Describe the bug**
So I am very aware this might not be a bug but me missing the point – yet I spent quite a bit of time figuring this out and to no result. 

I am having difficulties changing the images in a Media card constellation: I see the "Upload media", but I want to change the placeholders of the card or even delete some of them so I can have only one image (as I got on the cards I see on the homepage). 

**To Reproduce**
Add Media card constellation

**Expected behavior**
Tap on images to edit media OR
Find a "+"/"-" button to add/delete media from placeholders OR
FInd an "Edit media" button to replace placeholders

**Screenshots**
<img width="1377" alt="Screenshot 2020-11-09 at 21 08 29" src="https://user-images.githubusercontent.com/15910943/98596708-baa6cb80-22cf-11eb-9239-7be9b9fe3588.png">

**Comment by georgeolaru** [comment]
Hey @ilincaroman! I'm surprised by your confusion, but I confess that it's not the first time that I've seen users in this context that couldn't find the "Change Media" button. I'm sorry about this.

To shed some light on how it works, the very first images that appear when you insert the Media Card block are simply placeholders. Their role is to give you a glimpse into how the card might look. When you add your images, those placeholders will be removed.

I made a screen recording to see how it works https://cln.sh/krRgz1

---

I'm thinking about two things that could improve both the discoverability and the overall editing experience:
1. Add a `Change Media` button over all those placeholders, as we did for the Cards Collection block — it should solve the discoverability problem.
2. In the overlay Modal, use the default Create Gallery interface to select and reorder multiple images. Now you need to hold the `Shift` key to select multiple images, which is another discoverability problem. Note that it seems that we had this behavior in the first place, but it got lost or changed in the meantime (see the [documentation](https://pixelgrade.com/docs/rosa2/blocks/media-card/))

@razwan, can you have a look over this issue?

**Comment by ilincaroman** [comment]
@georgeolaru Ohh! I was pretty sure that button would change the media, but I think I got confused that I wasn't seeing those placeholders anywhere else? I would expect to see them inserted as actual media in the Gallery editor so I can replace them. The fact that it's blank made me think that it's not the right place and it would just insert another image (where? I don't really know :) )

**Comment by razwan** [comment]
Hello!

So the way the advanced gallery works, changed when I added video support. That is because the WordPress modal for editing galleries doesn't actually support video attachments. That is why I had to resort to the default media library modal, where you have to you CMD or Shift to select multiple images.

Made some changes to address this issues in https://github.com/pixelgrade/nova-blocks/pull/246

**Comment by georgeolaru** [comment]
Good work @razwan! It works as expected and it's definitely easier to discover, even the _video_ feature. 😎

![Screenshot2020-11-11 at 08 58](https://user-images.githubusercontent.com/1632775/98779205-2f772400-23fc-11eb-9b6f-ef7371aa2379.gif)

---

Two things that I'm noticing before closing this issue:

1. [ ] The overlay appears only when the block is selected, but it works if I click (see this [screen recording](https://cln.sh/gMZGK9)). Can we have the hover effect even when the block is not selected (like Buttons block does)?
2. [ ] The hover effect doesn't seem to have a transition for the opacity of the `.gallery__grid` and it shows sharply, unlike the "Change Media" button transition.
