### ISSUE TITLE
Logo not displaying in header when at top of a page

### ISSUE THREAD

**Issue by ilincaroman** [pixelgrade/nova-blocks#243]
**Describe the bug**
I set a logo in "Site identity", but it doesn't display at the top of the page when loading it. On scroll it appears in the header.

**To Reproduce**
Go on any page on https://staging2.illustration.ilincaroman.com/ and watch the top space for logo.

**Expected behavior**
Display logo in the middle of the header when page is loaded completely.

**Screenshots**
<img width="1374" alt="Screenshot 2020-11-09 at 21 43 11" src="https://user-images.githubusercontent.com/15910943/98600002-cea0fc00-22d4-11eb-8143-758684a42caa.png">

**Comment by madalingorbanescu** [comment]
Hello, again @ilincaroman,

There are two sections where you can set your logo in _Site Identity_: **Logo** and **Logo while on Transparent Header**. You probably didn't set the logo for the transparent header.

Please let me know how that worked for you.

**Comment by ilincaroman** [comment]
@madalingorbanescu This worked, thanks! I might suggest adding more details into why there is the need for two logos? Now I remember this was for contrast reasons (white vs. photo background), but has potential of being ignored.

**Comment by madalingorbanescu** [comment]
The reason for the two logos is to fix the contrast issues if there are any. On most of our pages, the first block used is a Hero Block. Whenever the first block on a page is a Hero Block, the header will be transparent and with the header being transparent there is a big change there will be a contrast issue with the logo.

For example on our demo of Rosa2, the default logo is using a dark color and this color is not visible the header is transparent.

![image](https://user-images.githubusercontent.com/46342490/98676188-f55a4380-2363-11eb-93c0-5962f92d37b7.png)

_Logo while on Transparent Header_ to the rescue:
![image](https://user-images.githubusercontent.com/46342490/98676319-1fac0100-2364-11eb-8acf-41b11a17ed20.png)

Until now, we didn't think that it can be ignored, but considering your experience I think we can use the default logo as a fallback if the second one is not used.

**Comment by ilincaroman** [comment]
That's a good idea with the fallback as well. I have nothing more to add on this issue, so I'll let you guys at it :) Thanks @madalingorbanescu!

**Comment by madalingorbanescu** [comment]
The fix will be applied in our theme Rosa2, so I am going to close the issue here and continue on the theme's repo.

Thank you for contributing to our products 😁
