### ISSUE TITLE
[Announcement bar] Announcement bar displaying even if I don't have it set

### ISSUE THREAD

**Issue by ilincaroman** [pixelgrade/nova-blocks#244]
**Describe the bug**
Announcement bar is displaying with no content even if I don't have it set anywhere. I usually expect to set it on the homepage in the Gutenberg builder, but I don't have it in the list of blocks. Is there another place this can be set? At this point it's not clear where I can set it (didn't find it in Customizer or any Gutenberg page).

**To Reproduce**
Go on any page of https://staging2.illustration.ilincaroman.com/. Announcement bar design displaying at the top, but not set anywhere.

**Expected behavior**
Don't display announcement bar if I don't have it set anywhere.

**Screenshots**
How it looks:
<img width="1680" alt="Screenshot 2020-11-09 at 21 44 22" src="https://user-images.githubusercontent.com/15910943/98600542-a239af80-22d5-11eb-935e-2db252d10b9f.png">

How the Homepage blocks list looks like:
<img width="290" alt="Screenshot 2020-11-09 at 21 51 18" src="https://user-images.githubusercontent.com/15910943/98600584-b5e51600-22d5-11eb-9fb9-c6bc4bd22c0e.png">

**Comment by madalingorbanescu** [comment]
Hey @ilincaroman,

Currently, Gutenberg is not allowing us to add a block and make it visible on every page. To solve this problem we have used a custom solution named Block Areas. These Block Areas are zones that are visible on every page of your website and these zones are Promo Bar, Header, and Footer.

In your case, you will want to edit the Block Area named **Promo Bar**. You can either delete the block from that zone, or you can convert this Block Area to a draft. In both cases, the Announcement Bar will not be visible anymore.

PS: After inspecting the mark-up on your website, I saw that your Promo Bar area has an OpenHours block inside, so it's not really empty.

Please let me know if that solved your problem.

**Comment by ilincaroman** [comment]
@madalingorbanescu Sorry, I'm not sure I can find the "Promo bar" Block area inserted anywhere on my Homepage blocks (in the screenshot that's the list of modules I have currently). Could it be that it's set on another page?

**Comment by madalingorbanescu** [comment]
Sorry @ilincaroman, my bad. It looks like I didn't provide any details about where you can find these Block Areas.

You can find all the available block areas in Appearance → Block Areas.
Also, more info about the Announcement Bar can be found [here](https://pixelgrade.com/docs/rosa2/blocks/announcement-bar/).

**Comment by ilincaroman** [comment]
SOrry for the late one @madalingorbanescu. It seems like now it works just fine and found the place where to edit it :)
