### ISSUE TITLE
Consider verbose options for customisation, rather than numerical labels

### ISSUE THREAD

**Issue by ilincaroman** [pixelgrade/nova-blocks#245]
**Is your feature request related to a problem? Please describe.**
In the Nova blocks I find it difficult to understand what each number represents for styling options. For example the Colour Contrast selector:

<img width="286" alt="Screenshot 2020-11-09 at 21 54 33" src="https://user-images.githubusercontent.com/15910943/98600900-2ab85000-22d6-11eb-97ab-48f270c5ff02.png">

I go with a "fail, rinse, repeat" approach, but it's costing me time to go through them and then memorise the value at which I was happy with the result – this slightly unpredictable behaviour affects my learning curve. 

Numbers are also too abstract to truly represent a UI composition. This contributes to difficulty of associating an option to a preferred setting. 

**Describe the solution you'd like**
When talking about customisations, use verbose labels that describe as much as possible – but in a concise way – the expected result. Another iteration on this would be actually using visual compositions.

**Comment by georgeolaru** [comment]
Thanks for your suggestions! 

We went with a "Low, Medium, High" style format:
![Screenshot 2022-06-24 at 10-16](https://user-images.githubusercontent.com/1632775/175483498-1d9aa9f0-1c4d-42c4-9b08-b085ed0a9891.jpg)
