### ISSUE TITLE
Cards Collection block: Option to disable cards from evenly spanning full-width

### ISSUE THREAD

**Issue by ilincaroman** [pixelgrade/nova-blocks#247]
**Is your feature request related to a problem? Please describe.**
I am trying to introduce a section that describes 7 categories (see screenshot). I am using "Cards collection" to create two rows, as it won't fit in one module. 

On the second row, I have 3 items. At the moment the whole container goes full width, with cards width spreading evenly (assume it's flex-box). This layout though gives more prominence to the second row, but I'd want to avoid that and keep an even feel so that the cards feel part of the same section and the relation is clear between them (i.e. they are on the same hierarchy).

**Describe the solution you'd like**
I'm not sure at this point, as I can see other cases rise as well: what if you want 3 on the first row and 2 cards on the second? Might be that there has to be a centre-align option for the row and a max-width of the cards that doesn't change based on the number of columns.

So:
– fixed width of cards
– centre-align row
– might be only an option of "fix cards width"/"evenly split cards on row". Wording may vary

**Describe alternatives you've considered**
At this point I can see how I can add another card with "View all products/collections" so I can balance the composition.

**Additional context**
<img width="1700" alt="Screenshot 2020-11-10 at 18 06 00" src="https://user-images.githubusercontent.com/15910943/98713339-6824e800-237f-11eb-940f-895a65709ed8.png">

**Comment by georgeolaru** [comment]
Now we do have an option to set the `Number of items per Row` that somehow helps in a few cases by simply throwing extra white space at the end of the row:

https://user-images.githubusercontent.com/1632775/175481982-306ea851-735d-41bf-88e0-1f3cff38b6a9.mp4

---

We still need to explore more paths to maintain the same weight of all the cards when they are in odd numbers, but for now, we will leave it as it is. 

Thanks again for reporting and suggestions!
