### ISSUE TITLE
[Advanced Gallery] Captions don't move along with images

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#258]
While playing around with the available options in the Gallery of the Stars block, I noticed that the captions do not seem to move in the same way the images do.

If an image is moving up or down, the caption seems to be fixed in the same spot. There are some settings where having a caption is not ideal, but in others, a caption can still work even if the images are arranged in a creative way.

The video below can better explain what I mean:
[captions in galleries.zip](https://github.com/pixelgrade/nova-blocks/files/5596873/captions.in.galleries.zip)

**Comment by georgeolaru** [comment]
@andreiungurianu The Advanced Gallery block uses a grid layout based on **containers** inside which images are placed and resized to stretch and fill the container or shrink and fit inside it (no crop).

**Captions** stays relative to the _container_ frame, not to the image inside — so the captions will work as you intend only when the images are set to stretch and fill the container:

https://user-images.githubusercontent.com/1632775/104712705-8a463800-572b-11eb-9eb9-17eadf86100e.mp4

---

Technically, now it's too complex to find a way to align the caption with images. If anything changes, we will come here and reopen this issue.

**Comment by andreiungurianu** [comment]
Thanks for the explanations @georgeolaru - it does help understand how the system works.
