### ISSUE TITLE
[Media Card] Aligning content to the right makes the button stick out

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#262]
When I align the content of a Media Card to the right, the button seems to stick out far too much.

I'm using Rosa2 1.6.3, Nova Blocks 1.7.1.

![image](https://user-images.githubusercontent.com/53944294/102627133-66093280-4150-11eb-95f1-4135390f7a67.png)

**Comment by madalingorbanescu** [comment]
The issue is related to Rosa2, so I am going to close here and continue on the theme's repo.
