### ISSUE TITLE
[Documentation] Managing comments and conversations

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/nova-blocks#278]
The documentation article for the Conversation System developed on https://github.com/pixelgrade/nova-blocks/issues/253

@andreiungurianu please take the stage ✍️

**Comment by andreiungurianu** [comment]
After many pings and back and forths with @georgeolaru - I have a promising draft [here](https://paper.dropbox.com/doc/vtpXDCk4eJwWr45n61DWt). @georgeolaru please take a look when you got the time.

**Comment by georgeolaru** [comment]
Great work @andreiungurianu! It's good to go from my side.

**Comment by andreiungurianu** [comment]
Thanks @georgeolaru and @oanafilip for the feedback. The article [is live](https://pixelgrade.com/docs/rosa2/social-networks/how-to-manage-comments/). 🎉
