### ISSUE TITLE
Extending the Header Layout System to Multiple Rows

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/nova-blocks#281]
The current header system In Rosa+Nova it’s based on **a single row of items** (e.g. menu items, logo, social icons, search) that can be moved around horizontally and resized to fit the user's needs. This limited system provides a great user experience but excludes some situations where extra elements are needed and cannot fit in a single row header without cluttering the layout.

Maintaining all the decisions made so far, I think we can go a step forward and extend the Header system to provide more flexibility for users and support more complex layout solutions.

## Main Goals
- Extend the current header system to support multiple rows of components.
- Be able to create Julia/ Felt, Hive, and Silk's theme header using the Rosa+Nova system.

## Proposal outline
I suggest limiting the header structure to a **3x3 matrix** as it provides a great balance of flexibility without overwhelming the users with too much complexity. 

[Here](https://www.figma.com/file/x3hxMaLar6GA2ZtDOHjO7q/LT-Pattern-Library?node-id=852%3A307) are some results that could come out of these constraints:

![Header structure](https://user-images.githubusercontent.com/1632775/105625580-eea37e80-5e32-11eb-8d12-b13497f40165.png)

And here is an example outlining the details of a triple-row header:

![Triple-row header](https://user-images.githubusercontent.com/1632775/105626165-d6cdf980-5e36-11eb-8795-abdf3fb40a44.png)

 

## Guidelines
- **Row Scopes:** while we don’t have much control over the content from each row, I think it’s useful to assign them some roles:
	- Only one row could have the scope of *Logo* → `.scope--logo`
	- Only one row could have the scope of *Primary Menu* `.scope--main-nav`
	- Only one row could be *Sticky* on scroll → `.scope--sticky`
		- If those two are not the same, the row with the Primary Menu should show on hover (e.g. [Heap](https://demos.pixelgrade.com/heap/)) or when scroll up (e.g. Felt)
- Blocks styling options
	- Each header row can have different color styling (e.g. we can make use of the new Color Palettes variations from Style Manager)
- Customizer options:
	- The current Logo and Header Height options from Customizer should be applied for the row with the "Logo" scope
	- The Navigation Items should all share the same color, fonts, and spacing options 
- If possible, use a single source for markup on mobile/desktop and explore a CSS-based solution to move the items around.

### Use cases and examples of Headers
In researching for a solution, I figure out a set of examples and references, both from our past experience and from other public sites, organizing them on two axes: by _complexity_ (number of elements) and by the _number of rows_ (1, 2 or 3): 

| ~           | Single-row                                                                                                                                                | Double-row                                                                              | Triple-row                                                                               |
| :---------- | :-------------------------------------------------------------------------------------------------------------------------------------------------------: | :-------------------------------------------------------------------------------------: | :--------------------------------------------------------------------------------------: |
| **Simple**  |             [Fargo](https://demos.pixelgrade.com/fargo/), [Aesop](https://www.aesop.com/de/en), [Venn Studio](https://www.vennstudiola.com/)              | [Hive](https://demos.pixelgrade.com/Hive/), [Minimalissimo](https://minimalissimo.com/) |                                            ∄                                             |
| **Medium**  | [Mailchimp](https://mailchimp.com/), [Shopify](https://www.shopify.com/), <br> [Squarespace](https://www.squarespace.com/), [Github](https://github.com/) |                        [The Times](https://www.thetimes.co.uk/)                         |                     [Interview](https://www.interviewmagazine.com/#)                     |
| **Complex** |                                                                             ∄                                                                             |  [Heap](https://demos.pixelgrade.com/heap/), [New Yorker](https://www.newyorker.com/)   | [Julia](https://demos.pixelgrade.com/julia/), [Silk](https://demos.pixelgrade.com/silk/) |

---

 @madalingorbanescu, you build a good chunk of the current header system, and I think you have the necessary skills to take it further. If you have any questions or want to discuss this further, give me a ping.

**Comment by madalingorbanescu** [comment]
Closed in a7bcd3640a673939484db9923fc2f519a7cb03b8
