### ISSUE TITLE
Extending the Posts Collection block with Carousel support

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#289]
At the moment, the Posts Collection block is capable of generating two types of grid: Classic and Parametric, the second being the one that offers a lot of versatility. Those options already offer a lot of flexibility and you can obtain great layouts, but there is room for improvement. And this is where Carousel steps in.

With Posts Collection and the [latest update for the header block](https://github.com/pixelgrade/nova-blocks/issues/281), we want to achieve [Felt](https://demos.pixelgrade.com/felt/) or [Julia](https://demos.pixelgrade.com/julia/) layouts using Nova Blocks.

All grids can be easily created using Posts Collection parametric layout, however, currently, we are missing an option to display posts as a carousel, like this:

![CleanShot 2021-02-16 at 10 03 31](https://user-images.githubusercontent.com/46342490/108034511-4d2cd880-703e-11eb-8ddb-98b607600f1d.gif)

## Guidelines
- The option for displaying posts inside a carousel should be in Grid Layout → Grid Anatomy.
- The following options should be available for the Carousel:
	- _Cards count_ - this option will control the number of posts available for the carousel.
	- _Items layout_  - this option will change the way that cards will be displayed inside the carousel and it will have two options: 
		- _Fixed Width_ (all card images will have the same height and width for their images - image height and format will be controlled from the Card Details section). 
		![image](https://user-images.githubusercontent.com/46342490/108036444-e78e1b80-7040-11eb-946b-e4a3273ba866.png)
		* When this option is selected, there will also be an option **Number of Items per Row**. This option will not be available for the _Variable Width_ layout, because there the number of items is based on the card image format.
		- _Variable Width_ (all card images will have the same height, but the width will be variable based on the original image format).
		
		![image](https://user-images.githubusercontent.com/46342490/108036612-215f2200-7041-11eb-9b03-018135a7e6dc.png)

	- _Show Pagination_ - when this option is enabled we will show pagination for the carousel items.
	
![image](https://user-images.githubusercontent.com/46342490/108036949-8fa3e480-7041-11eb-85ab-dbc9aa92d4d5.png)

**Comment by georgeolaru** [comment]
We implemented this using the Query Loop block and it's available for any Supernova block (Cards Collection, Hero, Media Card) that's placed inside a Query Loop.

Here is a demo: http://starter.pixelgrade.com/felt-lt
