### ISSUE TITLE
Extending the Slideshow block with source option

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#292]
Similar to https://github.com/pixelgrade/nova-blocks/issues/289

One of the latest missing pieces in creating [Julia](https://demos.pixelgrade.com/julia/) or [Felt](https://demos.pixelgrade.com/felt/) layout using Nova Blocks is a Slideshow that can handle posts, or any other source (eg. products).

![image](https://user-images.githubusercontent.com/46342490/108360926-81e58f00-71fa-11eb-9412-b8b4594f6594.png)

At the moment, the Block is pretty simple displaying images from a gallery, with their title and caption.

## Guidelines
- The option for selecting a source should be in a new section called _Source_. At the moment there should be two available options: gallery and posts.
- We need to control the content displayed on the slideshow, and my suggestion would be to use the same sections as Post Collection is using: _Display_ and _Content Filter_. 
	- _Display_ section -  options to show or hide: Title, Description, Buttons, Meta, and two more options to control primary and secondary metadata.
	- _Content filter_ - exactly the same options used in Posts Collection.
- An option that will show or hide the Pagination for the slideshow.

**Comment by georgeolaru** [comment]
We implemented this using the Query Loop block and it's available for any Supernova block (Cards Collection, Hero, Media Card) that's placed inside a Query Loop.

Here is a demo: http://starter.pixelgrade.com/felt-lt
