### ISSUE TITLE
Latest Chrome update breaks the blog layout

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#293]
@madalingorbanescu helped me with some investigations and it seems like the latest update from Chrome breaks the layout for the blog posts.

I first noticed this on [Acaju's website](https://la-acaju.ro/evenimente/) and then I also saw it in the demo for Rosa2 and Rosa2 Lite.

![CleanShot 2021-02-18 at 16 53 16](https://user-images.githubusercontent.com/53944294/108374615-d2181d80-7209-11eb-9e1e-546501db208c.png)

![CleanShot 2021-02-18 at 16 53 02](https://user-images.githubusercontent.com/53944294/108374617-d2b0b400-7209-11eb-8964-f4dca14fe396.png)

**Comment by madalingorbanescu** [comment]
After some investigations, I have found out the CSS causing that is in Rosa2, so I am going to continue on the Rosa2 repo.
