### ISSUE TITLE
[Conversation System] Style "No further comments..." message

### ISSUE THREAD

**Issue by vladolaru** [pixelgrade/nova-blocks#296]
I am not sure that we've considered this, but **when there are comments posted but the discussion is currently closed,** a message appears after the comments list. Maybe we should integrate it better in the layout.

![CleanShot 2021-03-09 at 10 03 24](https://user-images.githubusercontent.com/8830539/110438249-daec6880-80be-11eb-874e-f5c43cacb8c8.png)

As a side note, there is another message that appears related to the discussion being closed: **when there are no comments posted and the discussion is closed,** another message appears. Nothing else from the block is rendered. Just this message.

**Comment by georgeolaru** [comment]
@vladolaru Thanks for bringing this up!

### 1. No comments allowed
I imagine the case where there are no comments posted and no comments allowed (discussion closed), we should not display anything related to this feature. 

In my opinion, it means that the site admin is not looking to provide such a system to its site, so visitors shouldn't know about its possible existence (valid for posts, pages, or any other type). 

I'm not sure if there is an omission from WordPress core, but I'm not finding any good reasons to display the comments system from a user perspective. 

### 2. Notification message when the conversation ends
I think a notification message is relevant only in the context of a present discussion to let an interested contributor understand that the conversation has been closed by the site admin or the system automatically (e.g. after inactivity or a specific number of days)

As for styling, I explored a few [options](https://user-images.githubusercontent.com/1632775/110452285-b64bbd00-80cd-11eb-834b-4383bf2280ea.png) and, as usual, I think the one that works best is the obvious and simple one: bold text with a second divider to encapsulate the section that starts from the title. I also think that a `mailto:` link to the site admin would help the user if it feels stuck and still has something important to say.

![image](https://user-images.githubusercontent.com/1632775/110452244-adf38200-80cd-11eb-94be-85e6609ae7c6.png)
_Here is a Figma [link](https://www.figma.com/file/x3hxMaLar6GA2ZtDOHjO7q/LT-Pattern-Library?node-id=958%3A0) with the mockup._

---
I hope it helps! Let me know what you think.

**Comment by madalingorbanescu** [comment]
After a short discussion with @georgeolaru, it looks like there were some issues with spacing and the fact that the comment form was still visible even comments were closed.

The second issue was already fixed by @vladolaru on `master`, so I fixed only the issue with spacings.

Here is how it looks now:
![image](https://user-images.githubusercontent.com/46342490/110610898-57527a80-8197-11eb-8dc1-d9581b7bf1c8.png)

**Comment by georgeolaru** [comment]
Good job @madalingorbanescu! If there is no other input coming in, we can close this and move forward.
