### ISSUE TITLE
[Hero of the Galaxy] Buttons aligning option isn't working anymore after WordPress 5.7

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/nova-blocks#298]
In Hero of the Galaxy, when using buttons, the aligning option isn't working anymore.

![CleanShot 2021-03-12 at 10 57 26](https://user-images.githubusercontent.com/6790170/110916783-d5428d00-8321-11eb-9cb9-17d656433b81.gif)

**Comment by andreiungurianu** [comment]
The same seems to be true when the button is not in the Hero block, but inserted stand alone on a page.


https://user-images.githubusercontent.com/53944294/111784524-2a534580-88c4-11eb-9f59-9b444301aae9.mp4

**Comment by madalingorbanescu** [comment]
After some debugging, I have found out that the issue is from Rosa2, not from Nova Blocks, so I am going to move the issue to Rosa2 repo.
