### ISSUE TITLE
New "Sidecar" Block

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/nova-blocks#303]
Let's explore creating a `structural block` to help position _supporting content_ (sidebars) along with the main content while maintaining a close relationship between them (e.g. `primary` → main content vs. `secondary` → sidebar). 

Setting this type of hierarchy, we will be able to control the experience across the resolutions (from `desktop` to `mobile`) and adjust the sizes accordingly (e.g. hold a minimum `~300px` size for sidebars to handle banners and ads).

![image](https://user-images.githubusercontent.com/1632775/114014016-d7403300-9870-11eb-9984-603968bc225f.png)

## Guidelines

- At its most fundamental level, the `Sidecar` block should hold two areas—`main content` and `sidebar`—that can be used interchangeably (`left` or `right`)
- The `Sidecar` block can also be inserted inside the `main content` area to create some pretty nice [layouts](https://user-images.githubusercontent.com/1632775/114014292-1ec6bf00-9871-11eb-86c4-c5112b9f4a56.png). 
- A nice-to-have feature would be the option to have two sidebars upfront (`left` and `right`)

**Blocks Alignment inside `main content`area**
- A block aligned `left` or `right` inside the `main content` area should be pulled outside and placed inside the corresponding `sidebar` area (eg. pull quotes along the main story).
- It would be great if we can provide this functionality for all blocks that have support for the `alignment` feature (from `Group` to `Image` and `Text`) → see an [example](https://user-images.githubusercontent.com/1632775/114016366-6bab9500-9873-11eb-81b2-f79514280e7c.png) with a text as a sidenote.

#### Use cases
| Page         | Main content  | Sidebar content                                                                |
| ----------------- | ------------- | ------------------------------------------------------------------------------ |
| Single Post  | Main story    | Small bits of information, facts and additional information related to the story |
| Archive page | Posts list    |  Site tools like search, newsletter subscription, sharing options                              |
| Recipe Index | Recipes list  | Filtering by category                                                          |
| Shop Archive | Products list | Promotional tools like ads or banners, filtering by price and category                                                |

**Comment by madalingorbanescu** [comment]
Closed in https://github.com/pixelgrade/nova-blocks/pull/318
