### ISSUE TITLE
Unused Javascript loaded on certain pages

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#306]
While analysing the Performance for [Flair Scent](http://flairscent.ro/), a customer of Rosa2 & Nova blocks, I noticed two javascript elements loaded that might not be necessary.

Here's a screenshot:
![CleanShot 2021-04-26 at 14 08 25](https://user-images.githubusercontent.com/53944294/116073289-e0b30300-a698-11eb-821f-597e3a5cbe0a.png)

From what I can understand, one is for **Google maps API** - which loads even though those pages do not have the Maps block added. As for the other one (**…mediaelement/mediaelement-and-player.min.js**) I'm not sure if it's okay to be loaded or not.

**1. Google Maps API key**
I've run this test using [Page Speed Insights](https://developers.google.com/speed/pagespeed/insights/) and after some digging, I noticed that the Google Maps API key loads on these pages:

- Blog Archive
- Shop Main page
- Product Category pages

**2. Media element**
After a few tests, I concluded that the **…mediaelement/mediaelement-and-player.min.js** loads on every page of the website.

**Note:** I double checked the results from Flair Scent with the ones from our Rosa2 demo and they overlaped, meaning that the same behaviour can be observed in both cases.

**Comment by madalingorbanescu** [comment]
Hey @andreiungurianu,

Thank you for reporting this. After taking a closer look, I have found out that actually all blocks are loaded on pages mentioned by you.

Usually, if a block is not used on a page, we are _unloading_ the style and script for that block. However, it looks like we are doing that on singular pages (simple page or article), but we are ignoring special pages, like the ones mentioned by you.

@razwan do you know why we used `is_singular()` [here](https://github.com/pixelgrade/nova-blocks/blob/6575c263a00a6c8252a5e9d0e26d0d4e2440c9a0/lib/client-assets.php#L455)?

**Comment by razwan** [comment]
There's a comment above that line stating the fact that the is_singular check is weak, but it did it's job on singular pages where we had some confidence that we wouldn't remove script or styles for blocks used on that particular page. 
> // has_block() will only work for singular "views", since it will not look in inner blocks or work for loops of posts.

Until FSE is fully implemented and used consistently, we're pretty much in the dark with regards to how and where blocks may be rendered. I can't remember what were the issues when we did a more "aggressive" removal of unused script, or if we even did so.

However, you can try to find a more comprehensive condition when to remove unused scripts and styles.

**Comment by madalingorbanescu** [comment]
This will be solved by updating our logic to use:
```php
add_filter( 'should_load_separate_core_block_assets', '__return_true' );
```

The discussion will be continued [here](https://github.com/pixelgrade/nova-blocks/issues/332).
