### ISSUE TITLE
Slideshow Block: Provide controls to edit the title and the description of a slide

### ISSUE THREAD

**Issue by vladolaru** [pixelgrade/nova-blocks#32]
We rely on the title and the caption of the slide image to hold the contents. We should provide some easy controls to reach those and edit. Maybe a link to open the media modal right at that image.

**Comment by andreiungurianu** [comment]
@georgeolaru In my calls with Rosa 2 customers I have had the request to be able to add the Headline block inside the slideshow from two customers. Both wanted to be able to keep consistency and have their headlines match those provided by the Hero Block. With the current options, the titles for each slide look completly different than the rest (the media card has the same ones as well).

They also wanted to have the option to add the Headline block on each slide - so they could personalize the text.

I know that two customers out of 13 that I've talked with is not a lot, so I want to ping @alinclamba and @Alexandru-Teodorescu and ask them to let us know if they encountered the same feedback and extend this list.

At the same time, @georgeolaru - please let me know if this proposal is something not in line with the future plans for the Slideshow block.

**Comment by georgeolaru** [comment]
@andreiungurianu we have already implemented the functionality to show a Title and Description for each slide using the image meta fields _Caption_ and _Description_ — this use-case should be enough for most of our customers as I don't have any plans to move into a "slideshow builder" where you can craft each slide, rather use a _Source_ to output the content as a slideshow (eg. Gallery, Projects, Products). 

You might not be able to test this as it doesn't seem to work anymore. There was a time https://github.com/pixelgrade/nova-blocks/issues/165 when _Caption_ and _Description_ fields show on each slide, but I cannot replicate it anymore. @razwan can you have a look if something broke?

---
Now regarding the initial issue proposed by @vladolaru (which is not related to Andrei's mention)—I fully agree, some shortcuts to access the meta fields (or even inline editing like on the Gallery) could help manage the content easier. 

If anyone has any suggestions, feel free to post them here.

**Comment by andreiungurianu** [comment]
@georgeolaru thanks for the detailed answer and explanation. I understand now what are the future plans for the Slideshow block and why it's best to stay as is.

**Comment by georgeolaru** [comment]
Through the Supernova block now we can have Rich Text content for each slide:

![Screenshot 2022-06-24 at 10-36](https://user-images.githubusercontent.com/1632775/175486852-371312f7-8220-489f-899d-33482c82d741.jpg)
