### ISSUE TITLE
Make use of WordPress 5.8 block-styles loading enhancements

### ISSUE THREAD

**Issue by razwan** [pixelgrade/nova-blocks#332]
**Is your feature request related to a problem? Please describe.**
As of 5.8 WordPress introduces an opt-in feature for conditionally loading block assets
https://make.wordpress.org/core/2021/07/01/block-styles-loading-enhancements-in-wordpress-5-8/

```php
add_filter( 'should_load_separate_core_block_assets', '__return_true' );
```

**Describe the solution you'd like**
If the user has updated to 5.8 we should make use of this feature in both Nova Blocks and Rosa2. If not, we should load the current logic as a deprecated fallback.

**Comment by georgeolaru** [comment]
As we're at WordPress 6.0 I think we already implemented those suggestions.
