### ISSUE TITLE
Deprecated filters WordPress 5.8+

### ISSUE THREAD

**Issue by vladolaru** [pixelgrade/nova-blocks#334]
With WordPress 5.8, NovaBlocks generates notices like:

```
Deprecated: block_categories is deprecated since version 5.8.0! Use block_categories_all instead.
Deprecated: allowed_block_types is deprecated since version 5.8.0! Use allowed_block_types_all instead.
Deprecated: block_categories is deprecated since version 5.8.0! Use block_categories_all instead.
```

Here is the post documenting this: https://make.wordpress.org/core/2021/06/16/block-editor-api-changes-to-support-multiple-admin-screens-in-wp-5-8/

We should more to the new filters, but in a backward-compatible, clean way, meaning keep the main code clean with only the latest filters, but provide backward logic in a `deprecated` section/file.

**Comment by ZeiadSamir** [comment]
I’m a beginner front end and I’m going to build a full responsive website for an engineering consultant but i have some questions if any one can help please 

1- Is this kind of websites needs a huge database and wordpress dashboard or that point not very important?
2- And if so , should i build the data base first or after i finish the website and host it ? 
 
* note : this website contains only one form in contact us category that's all .

I will accept any advice ♥️

**Comment by georgeolaru** [comment]
We're at WordPress 6.0 I don't think we are affected by those filters anymore.
