### ISSUE TITLE
Components tabs jump to different levels when clicking between blocks

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#346]
It's a hard bug to explain, but I'll try to walk you through some examples:

- Click on a block (e.g., Media Card) and go to **Spacing and Sizing** and click the **Settings** tab
- Go to the **Color Signal** option and play around in the **Settings** tab but switch to **Customize** when exiting
- Go back to the **Spacing and Sizing** which will open in the **Settings** tab
- Click on another block that has the **Spacing and Sizing** setting (e.g., Cards Collection) and the tab will switch to **Customize**

https://user-images.githubusercontent.com/53944294/129208930-575b8b65-31ef-4057-9158-082128989fcd.mp4

Another example:

- Click on a block and play with the **Color Signal** option using the **Customize** tab and exit that setting
- Click on a different block and go to the **Spacing and Sizing** option — you'll find that the setting is set to **Customize** tab as in the issues I mentioned above); next, go to the **Settings** tab inside the **Spacing and Sizing** option
- Go back to the first block and click the **Color Signal** and you'll find the **Settings** panel opens instead of **Customize** one (the one from where we left in the first place)

https://user-images.githubusercontent.com/53944294/129213928-e4177668-8bf0-4220-afad-acd169753bc4.mp4

Example three (using two Media Card blocks)

https://user-images.githubusercontent.com/53944294/129212532-0955725f-bd80-4eb5-9bc2-ba84878c29cf.mp4

Example four (Two Media Cards using the **Spacing & Sizing** and the **Visual Balance** options)

https://user-images.githubusercontent.com/53944294/129213887-e8978bfb-c8b9-4db0-868c-b4387e412671.mp4

**Comment by georgeolaru** [comment]
@andreiungurianu I can confirm that when I'm on the `Settings` tab on the Media Card block and click on Cards Collection block the tab switches to `Customize`. 

The same happens with the **Space and Sizing** and **Color Signal** components.

https://user-images.githubusercontent.com/1632775/175478968-abf9ec1d-48fc-4e61-ad08-3b59d4006045.mp4

@razwan As it's not very consistent or urgent, please have a look whenever you have time.
