### ISSUE TITLE
[Posts Collection] Popper Grid Layout preset not selecting on click

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#355]
When I try to select the Popper preset, the selection goes to the "Just my Style" button. There seems to be a style change on click, so the functionality is there.

https://user-images.githubusercontent.com/53944294/132195114-7e017f61-6c34-4995-aae0-87505073d71c.mp4

I'm using Nova Blocks 1.13.2, Rosa2 1.13.0, WP 5.8

**Comment by georgeolaru** [comment]
It seems to work well now. Thanks for reporting!

https://user-images.githubusercontent.com/1632775/175477759-847edaeb-e913-4e2e-b0b4-5f65a44b2168.mp4
