### ISSUE TITLE
[Posts Collection] Horizontal Card Layout does not apply on Save

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#356]
While playing with the Grid Layout options, I noticed that when I use the Classic Grid with Horizontal Card Layout, the visual changes happen in the editor, but after I Save and check the live website, I see the Vertical layout applied.

When I went back to the page I noticed that the block setting was saved as Vertical and not Horizontal.

https://user-images.githubusercontent.com/53944294/132195640-4cc756cd-36e4-4201-8fa6-af4523b37136.mp4

I'm using Nova Blocks 1.13.2, Rosa2 1.13.0, WP 5.8

**Comment by georgeolaru** [comment]
@andreiungurianu I tested this on a recent version of the Nova Blocks plugin and now it works as intended.
