### ISSUE TITLE
[Super Nova] Issues & Improvements

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#357]
**Improvements**
- [x] Add a placeholder for the Collection title and subtitle.
- [x] Content to Media Spacing/Layout Gutter — Reduce max value.
- [x] Posts loading type and Prevent Duplicate Posts should be available only when the source type is posts.
- [x] Carousel — Improve numbers and arrow styling (both frontend and editor).
- [x] ~Carousel — Block missing padding-bottom when Pagination is disabled.~ (not needed).
- [x] Remove Number of items option from Content Loader. There is already an option is Collection Layout setting, that handles card items number.

**Issues**
- [x] When I select classic layout nothing is shown until I increase Item Count.
- [x] Card spacing options are not working.

**Currently not working**
- [x] Minimum Container Height
- [x] Image Container Height
- [x] Image Resizing

**Enhancement**
- [x] Minimum Container Height — Should be visible when Card is Stacked.
- [x] Image Container Height —  Should be visible when Card is not stacked.
- [x] Image Resizing —  Should be visible when Card is not stacked.
- [x] Content Width relative to Media Area —  Should be visible when Card is horizontal.
- [x] Content to Media Spacing/Layout Gutter —  Should be visible when Card is horizontal and vertical.
- [x] ~~Media Area Padding —  Should be visible when Card is not stacked.~~
- [x] Rename General section to Presets, because this is what we actually show there and it's easier for the user to understand. @georgeolaru 
- [x] General section (or Presets 😁 ) should not be available for Carousel or even Classic Grid, at least for the moment. @georgeolaru 

_This is a work-in-progress, so the issue will get updated every time we find new things that can be fixed or improved._

**Comment by madalingorbanescu** [comment]
- [ ] Item Count not updating.
- [ ] Button inside Supernova is not respecting alignment.
- [ ] Show Pagination inside Collection Layout should be removed because can be controlled from Elements Visibility.
- [ ] Slideshow Pagination should be on top of the slider.
- [ ] Prev arrow is not visible on frontend.
- [ ] Animation is broken for Slideshow on Frontend.
- [ ] Color classes are applied to every element.
- [ ] Arrow Colors should always match text color.
- [ ] Meta Is not showing.
- [ ] Connect Show Arrows attribute to control slider arrows and rename option to Arrows.
- [ ] Spacing between Post Collection Title and Supernova Items is too big.
- [ ] Sidecar Block styling is broken inside the editor.
- [ ] Frontend — extra padding applied on every block.
- [ ] Header should go transparent on different conditions (eg. First block is stacked and is 1 per row).

**Comment by madalingorbanescu** [comment]
- [ ] Add new control on Collection Layout to handle grid gap.

**Comment by madalingorbanescu** [comment]
- [ ] When the header is transparent, the content color signal should be equal to the content color signal applied on the first Supernova Block.
- [ ] Add spacing between collection title and supernova items.
- [ ] Carousel with Variable Width is not working. (editor)
- [ ] Carousel with Fixed Width is not working. (editor and frontend)
- [ ] Sidecar — sticky item not working and is also hidden.
- [ ] Some Supernova Items are missing descriptions inside the editor.
- [ ] When description is not visible for supernova item, post title has wrong spacing applied (editor)
- [ ] Sidecar content is missing padding left and right on mobile.

**Comment by georgeolaru** [comment]
@madalingorbanescu We've done more than enough on this issue 👏  let's close it for now.
