### ISSUE TITLE
Rosa2 Site limited to middle four columns after update

### ISSUE THREAD

**Issue by JDAguilarHN** [pixelgrade/nova-blocks#397]
**Describe the bug**
After update from both the theme and WordPress, the site now displays as if it were always on mobile... Disabling Nova Blocks fixes the issue, however it messes with the site's layout.

**To Reproduce**
Unsure how to reproduce, 

**Expected behavior**
I expected the site to be full width

**Screenshots**
![image](https://user-images.githubusercontent.com/44251233/166326355-44d58a4b-85dc-4d0d-afb5-4599c15ce387.png)

**Additional context**
Unsure if related, but there is a share button now, it was not there before, I cannot find a way to disable it within Rosa2's configuration / menu

**Comment by georgeolaru** [comment]
Thanks for reporting this @JDAguilarHN! Please take a look at [this article](https://pixelgrade.com/docs/rosa2/troubleshooting/website-mobile-version-homepage-not-full-screen/) and let me know if it solves your problem.

**Comment by JDAguilarHN** [comment]
Much appreciated, this solved the problem.
________________________________
