### ISSUE TITLE
IE Edge - withParallax component doesn't work

### ISSUE THREAD

**Issue by acosmin** [pixelgrade/nova-blocks#40]
Hi! I was playing around with this component and noticed that blocks like Hero & Slideshow don't work in Edge. The problem is `getBoundingClientRect()` doesn't return the `y` position in this browser.

The solution would be to use `top` as they are the same.

https://github.com/pixelgrade/nova-blocks/blob/8496f795e0f00881b08db27ea387d3df199af532/src/components/with-parallax/index.js#L64-L66

https://github.com/pixelgrade/nova-blocks/blob/8496f795e0f00881b08db27ea387d3df199af532/src/components/with-parallax/index.js#L76

You should change `containerBox.y` with something like `positionTop = containerBox.y || containerBox.top`

**Comment by razwan** [comment]
Hey @acosmin!

Thanks for pointing out the issue and also for suggesting a way to fix it. Please feel free to open a pull request whenever you have the solution for the issue and when you have the time to do so.

IE and Edge support isn't at all spot-on at the moment neither in the editor nor on the frontend but we will be working on that.
