### ISSUE TITLE
Parametric Grid on Cards Collection block does not seem to display correctly on mobile

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#405]
I tested this using the Julia LT demo and it seems like there's something broken in the mobile version of the Homepage. This might be happening on other pages, but for now, that homepage is the only one I noticed has issue
![CleanShot 2022-06-30 at 17 16 11](https://user-images.githubusercontent.com/53944294/176700366-e720c6fe-0965-4371-b3f2-49678a4b21be.png)

This was also reported by one of our [customers](https://secure.helpscout.net/conversation/1924037711/65425?folderId=6133056).

**Comment by georgeolaru** [comment]
+1 [67108](https://secure.helpscout.net/conversation/2017907424/67108?folderId=1135392)
