### ISSUE TITLE
Category archive loads posts that are from other categories

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#406]
A [customer](https://secure.helpscout.net/conversation/1924037711/65425/) reported that even if she has a single post in a category, when she tries to filter using the Recipe Index page from Julia LT (or by visiting the category arhive page), there are other posts that load as well.

I tested locally and I got the same results: created a "testing" category, assigned only 4 posts to it and then visited the category arhive page—multiple posts loaded.

https://user-images.githubusercontent.com/53944294/179489176-2b3cf90b-b4e0-40a3-9406-1a9cbffc0c17.mp4

I'm using Anima 2.0.9, WP 6.0.1, Nova Blocks 2.1.2, Gutenberg 13.6.0

**Comment by razwan** [comment]
The issue was on the demo content at http://starter.pixelgrade.com/julia-lt where the query loop block on the archive template wasn't set to inherit query from template. I've updated the demo content.
