### ISSUE TITLE
Blocks problem

### ISSUE THREAD

**Issue by klswim** [pixelgrade/nova-blocks#442]
Just installed wordpress 6.4.1 and Rosa LT from pixelgrade with gutenberg and nova blocks plugin.
When I want to edit the home page (or other page), the nova blocks doesn't seem to display correctly because i have this following message : 
This block has encountered an error and cannot be previewed.

I tried with PHP 8.0 or PHP 7.4. Same problem.

**Comment by georgeolaru** [comment]
Related to #445
