### ISSUE TITLE
Undefined index: source in lib/extras.php on line 353

### ISSUE THREAD

**Issue by loxK** [pixelgrade/nova-blocks#52]
**Describe the bug**
Notice error on 1.1.5

Notice: Undefined index: source in [redacted]/plugins/nova-blocks/lib/extras.php on line 353

Looking at the code there is:

```php
if ( ! isset( $attributes[ $key ] ) ) {

	    	if ( $attributes_config[ $key ][ 'source' ] === 'meta' ) {
```
Because of first condition the second one cannot be met. If $attributes[ $key ] isn't set, $attributes[ $key ] ['source'] can never be equal to the string  'meta'

**Comment by razwan** [comment]
Hey @loxK 
While the first condition tests the `$attributes` value, the second one tests `$attributes_config` meaning that both conditions can be met. However, I added a check for `$attributes_config[ $key ][ 'source' ]` 

Thanks for the heads-up!

**Comment by besieger1** [comment]
This is still a problem... on 1.1.5

**Comment by georgeolaru** [comment]
@razwan @madalingorbanescu does the problem still exist and we should reopen the issue or we can leave it closed?

**Comment by madalingorbanescu** [comment]
I've just tested the latest version of Nova Blocks and everything looks ok. 
@besieger1 the latest version of Nova Blocks is 1.1.6, make sure you are on the latest version.
