### ISSUE TITLE
Numeric value inputs in header settings are missing

### ISSUE THREAD

**Issue by loxK** [pixelgrade/nova-blocks#53]
**Describe the bug**
I use Firefox and version 1.1.5.

When in header settings in the customizer, the input fields to enter numeric values aren't there anymore:

![image](https://user-images.githubusercontent.com/136687/70190120-37890700-1749-11ea-8fbd-c86ff78cb66f.png)

**Comment by razwan** [comment]
@loxK this issue isn't related to Nova Blocks. 
Could you please open the issue on [pixelgrade/customify](https://github.com/pixelgrade/customify/issues/new) instead?
