### ISSUE TITLE
Notice: Undefined index error

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/nova-blocks#56]
A few _Rosa 2_ cutomers noticed warning on their websites:

> Notice: Undefined index: source in /var/www/wp-content/plugins/nova-blocks/lib/extras.php on line 353.

**Comment by madalingorbanescu** [comment]
The problem has been solved here: 70389bd96b98b24b1f1ab4681f5a4020bba00971
An update with this fix will be released soon.
