### ISSUE TITLE
Scroll and position indicator controls missing

### ISSUE THREAD

**Issue by loxK** [pixelgrade/nova-blocks#57]
Scroll and position indicator controls are missing since latest updates of the plugin and of Gutenberg:

![unnamed](https://user-images.githubusercontent.com/136687/70772875-f6889680-1dc9-11ea-9862-2a254f21ce51.png)

**Comment by loxK** [comment]
The fix brings back the controls. It works for position indicator but the scroll indicator doesn't appear on the front-end whatever the setting is set to.

**Comment by loxK** [comment]
![image](https://user-images.githubusercontent.com/136687/70838898-6f393280-1e5e-11ea-90c1-3f2803849f30.png)

![image](https://user-images.githubusercontent.com/136687/70838907-7c562180-1e5e-11ea-999a-00360553be85.png)

**Comment by georgeolaru** [comment]
@loxK Thanks for reporting these issues!

@madalingorbanescu can you please check if that option is only available for Rosa 2? If yes — can we enable it only on a per-theme basis?

**Comment by loxK** [comment]
Ant progress ? We bought the Rosa 2 them but this feature is still non functional. the settings now appear in editor but have no effect on the frontend.

**Comment by loxK** [comment]
I fixed it please merge.

I am wondering why you introduced another attribute called "scrollIndicatorBlock" as you didn't do such a thing for positionIndicators.

**Comment by razwan** [comment]
Hey @loxK 

There was only one little issue with your pull request as there was no need to call **setAttributes** twice [here](https://github.com/pixelgrade/nova-blocks/commit/3521a4f88c768146c7c5f8644aee25e3ecdbc8c2#diff-0a74b514f0016c16a0896e605dc7e301R91-R92). What you could have done is something like this:
```js
setAttributes( {
    scrollIndicatorBlock: nextScrollIndicator,
    scrollIndicator: nextScrollIndicator,
} );
```
But have no worries, I merged your pull request and the scroll indicator will be fixed in the next update.

Thanks for your contributions!

**Comment by razwan** [comment]
Forgot to mention something to answer your question.

At the time the meta attributes bug was present in Gutenberg, we introduced the **scrollIndicatorBlock** attribute to keep the option on every block, while we removed the positionIndicator toggle and set it to true by default. Or at least that was the intention.

Cheers.

**Comment by loxK** [comment]
Be aware that [it is not currently set to true by default](https://github.com/pixelgrade/nova-blocks/blob/master/lib/extras.php#L423). The fix fixes the behavior, but it is false by default, and does not take into account the previous value stored inn  scrollIndicator. Basically on updating, if users have enabled the scrollIndicator on some pages they will have to enable it again for each page again.
