### ISSUE TITLE
Render raw instead of filtered content in block areas render method

### ISSUE THREAD

**Issue by razwan** [pixelgrade/nova-blocks#59]
As mentioned in https://github.com/pixelgrade/rosa2/issues/43 using `the_content` function to output the content of a block area instead of choosing the filters we want to use on the content can lead to some weird issues like **Related Posts** from **Jetpack** being displayed in the first rendered Block Area.

@vladolaru do you have any input on this one?

**Comment by vladolaru** [comment]
@razwan I've replaced the `the_content` call from Block Areas with a custom method that will apply all the default filters on the raw post content, without calling the `the_content` filter. We may lose some extensibility this way, but it will be safe from those that consider that a call to `the_content` means the primary post content of a page (like Related Posts from Jetpack).

**Comment by razwan** [comment]
👍
