### ISSUE TITLE
Add Video Support to Hero Blocks

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/nova-blocks#60]
Let's explore the option to insert **self-hosted video** to create a looping visual element behind the content. 

Currently, the block breaks once you select a video file in the Media Library:
> This block has encountered an error and cannot be previewed.

**Comment by razwan** [comment]
This is working on the [1.2.0 branch](https://github.com/pixelgrade/nova-blocks/tree/1.2.0)
