### ISSUE TITLE
Media Card: Button color on Highlighted Content

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#68]
Button for add block should be white when content is Highlighted:
![image](https://user-images.githubusercontent.com/1632775/72813773-9c061400-3c6c-11ea-89df-6f6d3431fdd4.png)

**Comment by georgeolaru** [comment]
@madalingorbanescu I think it works fine as long as the **button** color is within the "Colors" section from the palette and the **background** is from the "Dark" or "White" sections. The same rule applies to the "Discover" subtitle.

Have you found other use-cases where there isn't enough contrast on the button and background?

**Comment by georgeolaru** [comment]
@madalingorbanescu a quick follow-up here — is this issue still relevant or we can close it?

**Comment by madalingorbanescu** [comment]
Hey @georgeolaru, sorry for taking so long to respond.
It looks like in the latest version of Gutenberg, the add block button has been changed and now it offers a better contrast on Highlighted content.

To answer your question, the issue is not relevant anymore, so I am going to close it.

**Comment by georgeolaru** [comment]
Thanks @madalingorbanescu!
