### ISSUE TITLE
New "Open Hours" Block

### ISSUE THREAD

**Issue by vladolaru** [pixelgrade/nova-blocks#81]
**Describe the solution you'd like**
A block that not only displayed the hours in a nice way but also used those hours to determine if the business is still open or let them know when it will be open again.

**Describe alternatives you've considered**
There is already our Open Hours plugin.

**Additional context**
We could have a more streamlined, more solid logic than Open Hours, with added interactivity. I think this is a well-suited job for a block to handle.

Inspiration partially came from here: https://block.garden/seeds/

**Comment by georgeolaru** [comment]
@madalingorbanescu would you be willing to explore a migration to the https://wordpress.org/plugins/open-hours/ widget to a block?

**Comment by georgeolaru** [comment]
@vladolaru I worked with Madalin and he is already on top of it and has a ready-to-test option on the [openhours-block](https://github.com/pixelgrade/nova-blocks/tree/openhours-block) branch. 

The whole system was recreated from the [Open Hours](https://wordpress.org/plugins/open-hours/) plugin and some improvements were done to the interface. Here is a short recording of how it works:

![2020-04-02 10-47-07 2020-04-02 10_47_53](https://user-images.githubusercontent.com/1632775/78223372-6b91f000-74cf-11ea-9c2b-83b1eded4185.gif)

---

@madalingorbanescu is there anything that stops us from merging this feature into master? Could you outline the steps that you envision before the release?

**Comment by vladolaru** [comment]
Nice work @madalingorbanescu @georgeolaru

**Comment by madalingorbanescu** [comment]
@georgeolaru the new block is ready, I just have to do some clean-up.

But keep in mind that this block is going to be used in Rosa2, and giving the fact that we have more block areas available there, we have to make sure that it will blend perfectly. 

For this to happen, I have to make some small adjustments in the Announcement Bar block and add some tweaks in Rosa2.

Also, if you found any other issues related to the block, let me know.

**Comment by madalingorbanescu** [comment]
@georgeolaru Can you help me with an icon for the new block?

**Comment by madalingorbanescu** [comment]
Here is the new block in action on Rosa2:

**Announcement Bar**
![image](https://user-images.githubusercontent.com/46342490/78246886-8de93500-74f2-11ea-9d3a-d46c82bbf2f6.png)

**Hero**
![image](https://user-images.githubusercontent.com/46342490/78246924-9d687e00-74f2-11ea-94b4-d49594d0c41d.png)

**Footer**
![image](https://user-images.githubusercontent.com/46342490/78247009-c1c45a80-74f2-11ea-8c8d-86dfb8c45a50.png)

**Comment by georgeolaru** [comment]
@madalingorbanescu That's looking great! Could you please make sure that the "Current Status" supports `<b>` and `<em>` tags?

As for your request, I attached the icon for the block (and [Google Drive](https://drive.google.com/drive/folders/1hFt2cGxp70C2bCmEmTenTj1UhHLFdreG) location).

[icon-openhours.svg.zip](https://github.com/pixelgrade/nova-blocks/files/4420891/icon-openhours.svg.zip)

**Comment by madalingorbanescu** [comment]
Awesome job with the icon @georgeolaru 👏

1. Now it supports HTML tags. Here is how it looks:
![image](https://user-images.githubusercontent.com/46342490/78251727-6dbd7400-74fa-11ea-8b7f-bc1714e383ea.png)

2. Here is the footer, with the vertical spacing adjustments:
![image](https://user-images.githubusercontent.com/46342490/78252047-e7edf880-74fa-11ea-80b0-9bfa2f756598.png)

**Comment by georgeolaru** [comment]
Thanks @madalingorbanescu! You did a great job too 👏
