### ISSUE TITLE
Special of the day Block

### ISSUE THREAD

**Issue by vladolaru** [pixelgrade/nova-blocks#82]
**Describe the solution you'd like**
A block that displays a calendar where you can input whatever will be the special that day. On the front end, it just shows whatever item is in the backend for that day. Useful for restaurants, schools, etc.

**Additional context**
Inspiration came from here: https://block.garden/seeds/

**Comment by georgeolaru** [comment]
@vladolaru The reference site doesn't seem to be live anymore. I will close this issue for now.
