### ISSUE TITLE
Add Support for Poster Image on Hero Videos

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/nova-blocks#83]
A while ago in https://github.com/pixelgrade/nova-blocks/issues/60 we had implemented support for background video in the Hero block as an auto-play option only.

@razwan I'm wondering if you think that we need to support the **poster image** attribute (as the default Video block does)  and if there is any use case when the video is not showing, and there is a need for a static image fallback.

Looking forward to your feedback. Thanks!

**Comment by razwan** [comment]
I don't see any use case where the poster image would be useful. Videos in the Hero blocks are automatically muted and set to autoplay. 

There may still be a tiny percentage of users with older versions of their mobile OS where the autoplay attribute wouldn't work, but I think it would only create confusion as the poster image would rarely be seen.

**Comment by georgeolaru** [comment]
@razwan got it! As long as the video is set to autoplay there is no need for a poster image.

I will close it for now and get back to it if more users will request this feature.

Thanks
