### ISSUE TITLE
Create a System for Vertical Alignment of Media Card Block

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/nova-blocks#87]
Let's explore a system for **vertically spacing** the Media Card block by increasing its offset (positive) from the adjacent blocks or decreasing the space and overlap them.

Besides the standard top/bottom block spacing, the Media Card block has two more options (https://github.com/pixelgrade/nova-blocks/issues/86 and content Vertical Alignment) that, while increasing the flexibility adds some extra complexity.

The spacing system should take into account the following three variables:
1. **Block Spacing** which is relative to the outer edge (like CSS `margin` area) and uses a 5-points scale relative to the spacing module (-2x, -1x, 0, +1x, +2x)
2. **Emphasis Spacing** which is visible when the _Emphasis Level_ is set to `Moderate` or `Highlighted` and it's relative to the inner edge. It's like CSS `padding` only that it supports negative spacing too and uses the same system as above  (-2x, -1x, 0, +1x, +2x)
3. **Vertical Alignment** that position the content relative to the block height (top, middle, bottom)

![image](https://user-images.githubusercontent.com/1632775/75042275-d4487e80-54c6-11ea-9dfe-5e54f2dc2bb2.png)

---

**The first phase** would be to add options for each use-case and "stress-test" how it handles all the possible scenarios (a randomize button could help tremendously to cover all sorts of cases).

![image](https://user-images.githubusercontent.com/1632775/75042698-8122fb80-54c7-11ea-9a7c-46ceba7419d5.png)

---

In **the second phase**, we could explore some rules that connect the options and make them easier to use while achieving better and consistent results.

For example, when the content is aligned to the **bottom** and the emphasis option is **negative**, the rule could be to subtract the space from the opposite (top) while adding to the same side (bottom):
![image](https://user-images.githubusercontent.com/1632775/75043106-28079780-54c8-11ea-80de-532d93b65713.png)

At the same time, when the content is aligned to the **middle**, the emphasis option is directly related to the value selected, both vertically and horizontally at the same time

![align-middle](https://user-images.githubusercontent.com/1632775/75039848-2fc43d80-54c2-11ea-8cc2-0a0511ab8ff1.jpg)

More mockups in [Figma](https://www.figma.com/file/LkOxQKLMqMpZwBJQiTmmuiYK/Plugin-Nova-Blocks?node-id=1572%3A0)
---

@razwan As usual, I believe there is room for your exploration right in the development and chance for other opportunities to emerge. I'm eager to finding out how it feels for you and make the necessary adjustments.

Let me know how it works or if you have any questions before moving forward with a prototype. Thanks!

**Comment by razwan** [comment]
Hey @georgeolaru,

I've managed to create a prototype for this feature and made [a screen recording](https://share.getcloudapp.com/yAuvvAxp) while fidgeting with the options here. 

Please let me know if things seem to work as expected so I can go ahead and cleanup up the code.
Cheers!
