### ISSUE TITLE
Hero: Improvements

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#92]
- [x] Remove ":" from panel title: https://share.getcloudapp.com/WnuNbw2v
- [ ] Maybe we should change _Enable scroll indicator_ label to just _Enable_ because the panel is already named Scroll Indicator. The same we should do with position indicators: https://share.getcloudapp.com/wbumWJ1o

~~With Announcement bar block visible, scroll button has a wrong position: https://share.getcloudapp.com/lluyJyZ1~~ - the problem was with theme, not the plugin.

**Comment by georgeolaru** [comment]
@madalingorbanescu (2) I'm thinking that the labels could be moved outside of a section or in the top toolbar — in this case, I do think that "Enable scroll indicator" label is more clear for a user rather than a simple "Enable" and I would suggest it to leave it like that.

**Comment by georgeolaru** [comment]
@madalingorbanescu can you close this issue now? It seems that the second point should not be addressed.

**Comment by madalingorbanescu** [comment]
@georgeolaru yes, thank you for pointing this.
