### ISSUE TITLE
Menu: Improve mobile spacings

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#93]
Add small margins for menu items on mobile: https://share.getcloudapp.com/12u1NOZx

**Comment by georgeolaru** [comment]
@madalingorbanescu I think the overall spacing of the site content looks good — it might be a better option to see if we can limit the width only for the highlighted item (eg. half space). What do you think?

![image](https://user-images.githubusercontent.com/1632775/75667112-ba096000-5c7f-11ea-8ba8-c92fd001feba.png)

**Comment by madalingorbanescu** [comment]
@georgeolaru Totally agree with you 😁
I will reduce the padding around the highlighted item and that should do it.
