### ISSUE TITLE
OpenTable: Improvements

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#94]
~~Fonts are too small: https://share.getcloudapp.com/qGuoKgep~~
- [x] With Gutenberg plugin activated, the block is not working.
- [x] On frontend, with horizontal layout, the button has a red border: https://share.getcloudapp.com/v1ureAJW
- [x] In editor, when using horizontal layout inside a smaller column, OpenTable logo has a wrong position: https://share.getcloudapp.com/7KuRmx4k

**Comment by georgeolaru** [comment]
@madalingorbanescu are those issues related to Rosa2? If yes, then we should move it to that repository (eg. the fonts should match the body and it does on our the [demo](https://demos.pixelgrade.com/rosa2/reservations/))

**Comment by madalingorbanescu** [comment]
@georgeolaru Regarding (1) you are right, we should move it to Rosa2 repository, but the other ones are related to the plugin.

**Comment by madalingorbanescu** [comment]
The block is now working with the latest version of Gutenberg plugin and WordPress 5.4.1 and I cannot replicate the other issues anymore.

**Comment by georgeolaru** [comment]
Good job @madalingorbanescu! Not forget to self-assign the issues that you solved.
